### ISSUE TITLE
read EINVAL

### ISSUE THREAD

**Issue by noose** [joyent/node#14147]
Hi,
I have strange problem. On one of our servers we're getting:

```bash 
timeout 60 xvfb-run --server-args="-screen 0, 640x480x24" --auto-servernum slimerjs /var/www/app/releases/20150326112757/app/webShots/external/shot.js "http://localhost/page" "/var/www/app/shot.jpg" 1224x935
 
 events.js:85
       throw er; // Unhandled 'error' event     
              ^     
  Error: read EINVAL
      at exports._errnoException (util.js:746:11)     
      at Pipe.onread (net.js:550:26) )
```

Shot is black when received that error. We do something like 40-50 shots / minute and on that one server I'm getting that error every time. On second server (twin server - cloned instance on ec2) I'm receiving that error something like 1 per hour (so it's one per 2.5-3k shots).
What can I do?

```bash
$ npm -v
2.7.3
$ node -v
v0.12.0
$ slimerjs -v
Innophi SlimerJS 0.9.5, Copyright 2012-2015 Laurent Jouanneau & Innophi
$ uname -a
Linux shots-2 3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:22:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.1 LTS
Release:	14.04
Codename:	trusty
```

**Comment by noose** [comment]
I'm suppose that's nodejs error not a slimerjs :-)

**Comment by misterdjules** [comment]
Thanks for filing this issue!

Ideally, we would need a way to reproduce it. Is it possible for you to provide us with the smallest amount of code that reproduces the problem? I guess that would be what's in `/var/www/app/releases/20150326112757/app/webShots/external/shot.js` but only what's relevant to this problem.

Also, could you please paste two separate outputs of the same command failing:
1) Ran with `NODE_DEBUG` set to `net`.
2) Ran with a tracing tool like strace or dtruss.

Thank you!

**Comment by jasnell** [comment]
@noose ... any updates on this?

**Comment by jasnell** [comment]
Closing due to lack of activity and detail. Can reopen if necessary
