### ISSUE TITLE
Unexpected end of input - Temporary debugger error

### ISSUE THREAD

**Issue by IonicaBizau** [joyent/node#14478]
It has just happened today. I'm not sure if we should take care about this error since it was temporary.

Anyway, this is the error:

```sh
$ node debug `which foo` some args
< debugger listening on port 5858
connecting...There was an internal error in Node's debugger. Please report this bug.
Unexpected end of input
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Protocol.execute (_debugger.js:131:43)
    at Client.<anonymous> (_debugger.js:175:14)
    at Client.emit (events.js:95:17)
    at Client.<anonymous> (_stream_readable.js:765:14)
    at Client.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Client.Readable.push (_stream_readable.js:128:10)
```

Where `foo` is a command line application.

**Comment by jasnell** [comment]
What's the actual issue here?

**Comment by IonicaBizau** [comment]
Closing it. It didn't appear again. :smile:
