### ISSUE TITLE
Help with crypto

### ISSUE THREAD

**Issue by santosguilherme** [joyent/node#20983]
I created ciphertext with javax.crypto.Cipher org.apache.commons.codec.binary.Base64 and using Java like following:

```java
import java.security.NoSuchAlgorithmException;
import java.security.NoSuchProviderException;

import javax.crypto.Cipher;
import javax.crypto.NoSuchPaddingException;
import javax.crypto.SecretKey;
import javax.crypto.spec.SecretKeySpec;

import org.apache.commons.codec.binary.Base64;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public final class PwdCipher {

    private static final Logger LOG = LoggerFactory.getLogger(PwdCipher.class);

    private static final int BASE64_ARG0 = 32;

    private static final String SECRET = "tvnw63ufg9gh5392";

    private static byte[] linebreak = {};
    private static SecretKey key;
    private static Cipher cipher;
    private static Base64 coder;

    static {
            key = new SecretKeySpec(SECRET.getBytes(), "AES");
            try {
                cipher = Cipher.getInstance("AES/ECB/PKCS5Padding", "SunJCE");
            } catch (NoSuchAlgorithmException | NoSuchProviderException | NoSuchPaddingException e) {
                LOG.debug("Erro ao criar encriptador.", e);
            }
            coder = new Base64(BASE64_ARG0, linebreak, true);
    }

    private PwdCipher(){
    }

    public static synchronized String encrypt(String plainText) {
        try {
            cipher.init(Cipher.ENCRYPT_MODE, key);
            byte[] cipherText = cipher.doFinal(plainText.getBytes());
            return new String(coder.encode(cipherText));
        } catch (Exception e) {
            throw new GdocException("Erro ao encriptar senha.", e);
        }
    }

    public static synchronized String decrypt(String codedText) {
        try {
            byte[] encypted = coder.decode(codedText.getBytes());
            cipher.init(Cipher.DECRYPT_MODE, key);
            byte[] decrypted = cipher.doFinal(encypted);
            return new String(decrypted);
        } catch (Exception e) {
            throw new GdocException("Erro ao decriptar senha.", e);
        }
    }

}
```

I need to decrypt the text (encrypted with class PwdCipher) using Node.js, but when I use the following code:

```javascript
exports.decryptLdapPassword = function(password){
  var key = new Buffer('tvnw63ufg9gh5392');

  var ciphertext = password;

  var crypto = require('crypto');
  var decipher = crypto.createDecipher('aes-128-ecb', key);

  var decrypted = decipher.update(ciphertext, 'base64', 'utf8');
  decrypted += decipher.final('utf8');

  return decrypted;
};
```
It turns out the following exception:

```javascript
> crypto.js:323   var ret = this._binding.final();
>                           ^ TypeError: error:00000000:lib(0):func(0):reason(0)
>     at Decipher.Cipher.final (crypto.js:323:27)
>     at Object.exports.decryptLdapPassword (C:\ProjetosTFS\GDOC\fSuporte\GDoc\Versionado\Fontes\woodstock\server\api\service\service.util.js:14:25)
>     at Promise.<anonymous> (C:\ProjetosTFS\GDOC\fSuporte\GDoc\Versionado\Fontes\woodstock\server\api\service\service.controller.js:111:34)
>     at Promise.<anonymous> (C:\ProjetosTFS\GDOC\fSuporte\GDoc\Versionado\Fontes\woodstock\node_modules\mongoose\node_modules\mpromise\lib\promise.js:177:8)
>     at Promise.emit (events.js:95:17)
>     at Promise.emit (C:\ProjetosTFS\GDOC\fSuporte\GDoc\Versionado\Fontes\woodstock\node_modules\mongoose\node_modules\mpromise\lib\promise.js:84:38)
>     at Promise.fulfill (C:\ProjetosTFS\GDOC\fSuporte\GDoc\Versionado\Fontes\woodstock\node_modules\mongoose\node_modules\mpromise\lib\promise.js:97:20)
>     at Promise.resolve (C:\ProjetosTFS\GDOC\fSuporte\GDoc\Versionado\Fontes\woodstock\node_modules\mongoose\lib\promise.js:114:23)
>     at Promise.<anonymous> (C:\ProjetosTFS\GDOC\fSuporte\GDoc\Versionado\Fontes\woodstock\node_modules\mongoose\node_modules\mpromise\lib\promise.js:177:8)
>     at Promise.emit (events.js:95:17)
```
Any idea?

**Comment by misterdjules** [comment]
@indutny I'm not familiar with the crypto API, any thoughts?

**Comment by indutny** [comment]
Will look into it tomorrow.

**Comment by indutny** [comment]
@santosguilherme may I ask you to provide the data that fails to decrypt? Thanks a lot!

**Comment by saquibkhan** [comment]
Hi,
I think the problem is with padding you have used for encrypting **PKCS5Padding**. Node supports below padding:
1. RSA_PKCS1_PADDING       1
2. RSA_SSLV23_PADDING      2
3. RSA_PKCS1_OAEP_PADDING  4
4. RSA_X931_PADDING        5
5. RSA_PKCS1_PSS_PADDING   6

I can see Node is giving this error **EVP_R_BAD_DECRYPT**

@indutny  You can find following [test script](https://gist.github.com/saquibkhan/608f5a0cc33650c5590d) to reproduce the issue .

**Comment by indutny** [comment]
@saquibkhan are you sure that `yV0V7itTsTTZy0Qgjn_ndg` is in base64 encoding? It doesn't look like it ;)

**Comment by indutny** [comment]
Also, OpenSSL is using PKCS7Padding which is identical to PKCS5Padding in almost every sense.

**Comment by saquibkhan** [comment]
I used below java code to generate encrypted text :-)
```
import java.security.NoSuchAlgorithmException;
import java.security.NoSuchProviderException;

import javax.crypto.Cipher;
import javax.crypto.NoSuchPaddingException;
import javax.crypto.SecretKey;
import javax.crypto.spec.SecretKeySpec;

import org.apache.commons.codec.binary.Base64;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public final class PwdCipher {

    private static final Logger LOG = LoggerFactory.getLogger(PwdCipher.class);

    private static final int BASE64_ARG0 = 32;

    private static final String SECRET = "tvnw63ufg9gh5392";

    private static byte[] linebreak = {};
    private static SecretKey key;
    private static Cipher cipher;
    private static Base64 coder;

    static {
            key = new SecretKeySpec(SECRET.getBytes(), "AES");
            try {
                cipher = Cipher.getInstance("AES/ECB/PKCS5Padding", "SunJCE");
            } catch (NoSuchAlgorithmException | NoSuchProviderException | NoSuchPaddingException e) {
                LOG.debug("Erro ao criar encriptador.", e);
            }
            coder = new Base64(BASE64_ARG0, linebreak, true);
    }

    public static void main(String args[]){

        String encryptedText =  encrypt("Hello NodeJs");
        System.out.println(encryptedText);  
    }  


    private PwdCipher(){
    }

    public static synchronized String encrypt(String plainText) {
        try {
            cipher.init(Cipher.ENCRYPT_MODE, key);
            byte[] cipherText = cipher.doFinal(plainText.getBytes());
            return new String(coder.encode(cipherText));
        } catch (Exception e) {
            //throw new Exception("Erro ao encriptar senha.", e);
            return "";
        }
    }

    public static synchronized String decrypt(String codedText) {
        try {
            byte[] encypted = coder.decode(codedText.getBytes());
            cipher.init(Cipher.DECRYPT_MODE, key);
            byte[] decrypted = cipher.doFinal(encypted);
            return new String(decrypted);
        } catch (Exception e) {
            //throw new Exception("Erro ao decriptar senha.", e);
            return "";
        }
    }

}


```

**Comment by indutny** [comment]
@saquibkhan well, this is not a base64, and I think it is the reason why it doesn't work.

AFAIK, `coder = new Base64(BASE64_ARG0, linebreak, true);` means that will work in URL-safe mode. May I ask you to replace the `true` with `false` and paste your data here again (if it still won't work).

**Comment by indutny** [comment]
Nah, forget about it.

The real problem is this, it should be `createDecipheriv`:

```javascript
  var decipher = crypto.createDecipheriv('aes-128-ecb', key, new Buffer(0));
```

See **NOTE** here: https://iojs.org/api/crypto.html#crypto_crypto_createcipher_algorithm_password . Default key derivation algorithm is using MD5, while your code is supplying the key AS IT IS.

**Comment by saquibkhan** [comment]
false gives this ```yV0V7itTsTTZy0Qgjn/ndg==```

Note: I am successfully able to decrypt using java decrypt function.

Please find my logs on node v0.10.30 below:
```
crypto.js:337
  this._binding.init(cipher, toBuf(password));
                ^
Error: Must give cipher-type, key as argument
    at new Decipher (crypto.js:337:17)
    at Object.Decipher (crypto.js:334:12)
    at decrypt (/SAQUIB/gitHub/node-bugs/crypto/crypto.js:8:25)
    at Object.<anonymous> (/SAQUIB/gitHub/node-bugs/crypto/crypto.js:17:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

**Comment by saquibkhan** [comment]
Note: When i try to use AES/ECB/128 online encrypt/decrypt tool it ask me to enter secret of 24 bytes, and the secret mentioned in above java code is less than 24 bytes ``` private static final String SECRET = "tvnw63ufg9gh5392";```

**Comment by indutny** [comment]
@saquibkhan have you seen my comment about `crypto.createDecipheriv`?

**Comment by saquibkhan** [comment]
@indutny yes, great catch thanks :+1:  ```crypto.createDecipheriv``` works, Actually i was just debugging this issue and trying to help you guys to resolve the same :-)

**Comment by indutny** [comment]
Haha, yeah! I figured ;)

**Comment by santosguilherme** [comment]
yeah, works!! Thanks @indutny @saquibkhan!!
