### ISSUE TITLE
Add a --frozenGlobal flag

### ISSUE THREAD

**Issue by thejh** [joyent/node#2488]
How about adding a flag `--frozenGlobal` that, just before the user code gets executed, does `Object.freeze(global)`? Code example:

    a=1
    console.log(a)

Effect:

    ReferenceError: a is not defined
        at Object.<anonymous> (/home/jann/tmp/test.js:2:13)
        at Module._compile (module.js:432:26)
        at Object..js (module.js:450:10)
        at Module.load (module.js:351:31)
        at Function._load (module.js:310:12)
        at Array.0 (module.js:470:10)
        at EventEmitter._tickCallback (node.js:192:40)

It would be even cooler to already get an error on assignment to global, not just on usage, but that would probably require making the global object a proxy.

**Comment by jasnell** [comment]
@joyent/node-coreteam is this something that we'd actually ever do?

**Comment by cjihrig** [comment]
@jasnell I think it's highly unlikely.

**Comment by dayuoba** [comment]
some module add object on global,if `freeze(global)` may cause problem
