### ISSUE TITLE
Crash on request.

### ISSUE THREAD

**Issue by bushev** [joyent/node#25579]
I can only provide the error descripton. Node.js Express application crashed, seems on broken network package.  

Version: v0.10.25

```
2015-06-25T08:31:48.794Z - error: uncaughtException: read ECONNRESET date=Thu Jun 25 2015 11:31:48 GMT+0300 (MSK), pid=23606, uid=0, gid=0, cwd=/, execPath=/usr/bin/nodejs, version=v0.10.25, argv=[/usr/bin/node, /rp/node/app.js], rss=154218496, heapTotal=133715376, heapUsed=77385808, loadavg=[0.11474609375, 0.16064453125, 0.21923828125], uptime=2909161.949307619, trace=[column=11, file=net.js, function=errnoException, line=901, method=null, native=false, column=19, file=net.js, function=TCP.onread, line=556, method=onread, native=false], stack=[Error: read ECONNRESET, at errnoException (net.js:901:11), at TCP.onread (net.js:556:19)]
```

**Comment by CGavrila** [comment]
By `request` do you mean the npm module?

Even so, `ECONNRESET` is a perfectly valid way to have your application crashed, depending on what you're doing. Not exactly sure what you're doing, but you might want to add an `on('error', function() { dosomething(); })` somewhere in your code to catch that exception.

**Comment by bushev** [comment]
Hello Cristian!

No, I don't mean `requestjs`. I mean HTTP request.

I tried to implement workarounds, but them unfortunately doesn't works..

 1) Use `process.on`: (Didn't help - callback is never called)

```
process.on('uncaughtException', function (err) {
    console.log('uncaughtException: ' + util.inspect(err));
});
```

 2) Use nginx as a frontend. Didn't help too.

I also tried to install `longjohn` node nodule. Unfortunately in doesn't show any helpfull info for you.

```
2015-06-26T12:21:44.639Z - error: uncaughtException: read ECONNRESET date=Fri Jun 26 2015 15:21:44 GMT+0300 (MSK), pid=13655, uid=0, gid=0, cwd=/, execPath=/usr/bin/nodejs, version=v0.10.25, argv=[/usr/bin/nodejs, /rp/node/app.js], rss=176439296, heapTotal=155480960, heapUsed=78975512, loadavg=[1.74462890625, 1.552734375, 0.888671875], uptime=3009357.792995188, trace=[column=11, file=net.js, function=errnoException, line=901, method=null, native=false, column=19, file=net.js, function=onread, line=556, method=null, native=false, column=null, file=---------------------------------------------, function=null, line=null, method=null, native=null, column=15, file=net.js, function=fireErrorCallbacks, line=440, method=null, native=false, column=3, file=net.js, function=Socket._destroy, line=472, method=_destroy, native=false, column=10, file=net.js, function=onread, line=556, method=null, native=false], stack=[Error: read ECONNRESET,     at errnoException (net.js:901:11),     at onread (net.js:556:19), ---------------------------------------------,     at fireErrorCallbacks (net.js:440:15),     at Socket._destroy (net.js:472:3),     at onread (net.js:556:10)]
```

**Comment by CGavrila** [comment]
Sort of strange that `process.on('uncaughtException', ...)` doesn't work. Maybe you don't define it properly?

Have you tried something like this?
```
req.on('error', function(e) {
  console.log('Error: ' + e.message);
});
```
`req` is supposed to be the result of `http.request()`.

Otherwise, I suppose the best thing to do would be to try and replicate the error within a small example and post it here.

**Comment by bushev** [comment]
Cristian, I'm sorry.

I found the trouble in my module. Lets cancel this ticket.
