### ISSUE TITLE
invalid argument: hints must use valid flags

### ISSUE THREAD

**Issue by gentlecolder** [joyent/node#25599]
E:\lingzhihong\working\dyndns>node getip2.js
E:\lingzhihong\working\dyndns\getip2.js:80
      throw new TypeError('invalid argument: hints must use valid flags')
            ^
TypeError: invalid argument: hints must use valid flags
    at Object.dns.lookup (E:\lingzhihong\working\dyndns\getip2.js:80:13)
    at Socket.connect (net.js:926:9)
    at Agent.exports.connect.exports.createConnection (net.js:92:35)
    at Agent.createSocket (_http_agent.js:194:16)
    at Agent.addRequest (_http_agent.js:166:23)
    at new ClientRequest (_http_client.js:154:16)
    at Object.exports.request (http.js:49:10)
    at Object.exports.get (http.js:53:21)
    at Object.<anonymous> (E:\lingzhihong\working\dyndns\getip2.js:121:9)
    at Module._compile (module.js:460:26)

**Comment by gentlecolder** [comment]
why i cannot 

dns.lookup=function(hostname, options, callback) {
  var hints = 0;
  var family = -1;

  // Parse arguments
  if (hostname && typeof hostname !== 'string') {
    throw TypeError('invalid arguments: hostname must be a string or falsey');
  } else if (typeof options === 'function') {
    callback = options;
    family = 0;
  } else if (typeof callback !== 'function') {
    throw TypeError('invalid arguments: callback must be passed');
  } else if (util.isObject(options)) {
    hints = options.hints >>> 0;
    family = options.family >>> 0;

    if (hints !== 0 &&
        hints !== exports.ADDRCONFIG &&
        hints !== exports.V4MAPPED &&
        hints !== (exports.ADDRCONFIG | exports.V4MAPPED)) {
      throw new TypeError('invalid argument: hints must use valid flags');
    }
  } else {
    family = options >>> 0;
  }

  if (family !== 0 && family !== 4 && family !== 6)
    throw new TypeError('invalid argument: family must be 4 or 6');

  callback = makeAsync(callback);

  if (!hostname) {
    callback(null, null, family === 6 ? 6 : 4);
    return {};
  }

  var matchedFamily = net.isIP(hostname);
  if (matchedFamily) {
    callback(null, hostname, matchedFamily);
  z  return {};
  }

  var req = new GetAddrInfoReqWrap();
  req.callback = callback;
  req.family = family;
  req.hostname = hostname;
  req.oncomplete = onlookup;

  var err = cares.getaddrinfo(req, hostname, family, hints);
  if (err) {
    callback(errnoException(err, 'getaddrinfo', hostname));
    return {};
  }

  callback.immediately = true;
  return req;
};

**Comment by gentlecolder** [comment]
source code:
.......
.......
var request = require('http');
var fs = require('fs'); 
request.get('http://WWW.google.COM',function(res){ 
           var content='';
           res.on('data', function (chunk) {
		   content=content+chunk;
           console.log('BODY: ' + chunk);
		   console.log(content);
          });
            fs.readFile('ipinfo.txt', 'utf-8', function (err, data) {
            if (err) {
             console.log("FATAL An error occurred trying to read in the file: " + err);
             process.exit(-2);
                      }else{
  // Make sure there's data before we post it
               console.log(data); 
               
			 // var neirong=JSON.parse(content);
              console.log(content);			  
            if(content==data){                     
               console.log("ip is not changed");
            }else{

			 request.get('http://WWW.GOOGLE.COM',function (res) {
            if (err) {
             console.log("FATAL An error occurred trying to read in the file: " + err);
             process.exit(-2);
                      }
					  
					  else{
					  console.log(res.statusCode);
					  }
			});
            fs.writeFile('ipinfo.txt', content, 'utf-8', function(err){
                      if(err){
                        console.log('FAILED');
                         }else{
                       console.log('SUCCESS');
                         }
             });			
}}});
});

**Comment by gentlecolder** [comment]
fixed just add hints=0 before if else sentence to make the if condition=false, and dns wont throw any error
