### ISSUE TITLE
npm failed

### ISSUE THREAD

**Issue by gentlecolder** [joyent/node#25611]
function helloWorld(req, res) {
  res.end('Hello World!');
}

module.exports = helloWorld;

var connect=require('connect');
var helloworld=require('hello_world');
var app=connect();
app.use(helloworld);
app.linsten(80);

module.js:338
    throw err;
          ^
Error: Cannot find module 'escape-html'
    at Function.Module._resolveFilename (mo
    at Function.Module._load (module.js:278
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (connect\node_modules\finalhandler\index.js:15:18
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (modul
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310
    at Module.require (module.js:365:17)

window 7 node -v 12.2

**Comment by cjihrig** [comment]
Looks like you haven't installed `escape-html` properly. This doesn't appear to be related to Node core.
