### ISSUE TITLE
events.js:85 throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by urmilparikh** [joyent/node#25667]
events.js throws this error when output pipe is closed.

````
$ echo -e "console.log('hello'); \n console.log('world');" | node | grep -q hello
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write EPIPE
    at exports._errnoException (util.js:746:11)
    at Socket._writeGeneric (net.js:690:26)
    at Socket._write (net.js:709:8)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at Socket.Writable.write (_stream_writable.js:217:11)
    at Socket.write (net.js:634:40)
    at Console.log (console.js:55:16)
    at [stdin]:2:10
    at Object.exports.runInThisContext (vm.js:74:17)

$ node -v && npm -v && uname -a
v0.12.7
2.11.3
MINGW32_NT-6.2 SHINY 1.0.12(0.46/3/2) 2012-07-05 14:56 i686 unknown
````

**Comment by maatthc** [comment]
Check if it helps you: https://www.npmjs.com/package/epipebomb

**Comment by urmilparikh** [comment]
Yes, it helps!
Thank you!!
