### ISSUE TITLE
SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by heidarymr** [joyent/node#25813]
hi
i install node-v0.12.7-x64.msi and run as administrator
the install css-flip
the run below command:
can anyone help me?
> css-flip c:\css\style.css > c:\css\style.rtl2.css
SyntaxError: Unexpected identifier
    at Object.exports.createScript (vm.js:44:10)
    at REPLServer.defaultEval (repl.js:117:23)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:279:12)
    at REPLServer.emit (events.js:107:17)
    at REPLServer.Interface._onLine (readline.js:214:10)
    at REPLServer.Interface._line (readline.js:553:8)
    at REPLServer.Interface._ttyWrite (readline.js:830:14)
    at ReadStream.onkeypress (readline.js:109:10)
>

**Comment by cjihrig** [comment]
Can you try opening this issue on the css-flip repo first. We can reopen this if it's deemed to be a problem with Node.

**Comment by heidarymr** [comment]
dear cjihrig
i think this problem related to node.js
because when i try to run node.js with 'run as administrator' option and try to install r2:

> install r2
SyntaxError: Unexpected identifier
    at Object.exports.createScript (vm.js:44:10)
    at REPLServer.defaultEval (repl.js:117:23)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:279:12)
    at REPLServer.emit (events.js:107:17)
    at REPLServer.Interface._onLine (readline.js:214:10)
    at REPLServer.Interface._line (readline.js:553:8)
    at REPLServer.Interface._ttyWrite (readline.js:830:14)
    at ReadStream.onkeypress (readline.js:109:10)
>

**Comment by cjihrig** [comment]
`npm i css-flip` and `npm i r2` both seem to work fine for me (granted I'm not using Windows). Back to my original comment, can you try contacting the teams behind r2 and css-flip and letting them know you're having problems installing their modules.

**Comment by itig** [comment]
I keep having a similar problem. Every time I enter a file to open once in node mode on my mac's terminal i get back: unexpected identifier. I must be doing something wrong but am too new to it to know what.
