### ISSUE TITLE
adding some context to socket errors?

### ISSUE THREAD

**Issue by skoranga** [joyent/node#25884]
Debugging following errors without proper context is very hard.

```
Error: socket hang up
  at createHangUpError (http.js:1473:15)
  at CleartextStream.socketCloseListener (http.js:1523:23)
  at CleartextStream.emit (events.js:117:20)
  at tls.js:694:10
```

```
Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:550:26)
```

```
Error: connect ECONNREFUSED
   at exports._errnoException (util.js:746:11)
   at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
```

Is it possible to add some context like host and port information to it is easy to pin point the error or is there any way to get this information today somehow?

**Comment by cjihrig** [comment]
This probably won't make it into 0.10 or 0.12, but if I recall correctly, has already been added to io.js and the converged project.

**Comment by skoranga** [comment]
:+1: thanks @cjihrig for the update.
