### ISSUE TITLE
Issues after upgrade nodejs 0.10.4 to 0.12.7

### ISSUE THREAD

**Issue by whe4841** [joyent/node#25902]
opt/node-apps/Toyota-LMS/node_modules/jquery/node_modules/jsdom/lib/jsdom/level1/core.js:418
  set nodeName() { throw new core.DOMException();},
               ^
SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/opt/node-apps/Toyota-LMS/node_modules/jquery/node_modules/jsdom/lib/jsdom/level2/core.js:1:94)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

I found two related links, saying that there are some JDOM related issues with 0.12.7.

https://github.com/jquery/jquery/issues/2140
https://github.com/ucsf-ckm/symfony-emberjs-edition/issues/8

Please advise

Walter

**Comment by cjihrig** [comment]
I recommend asking on the jsdom repo, since that appears to be the source of the error. Based on one of the issues you linked to, you might need to use an older version of jsdom, or a newer version of node (see the nodejs/node repo).
