### ISSUE TITLE
node5: dns.V4MAPPED on Solaris causes tests to fail/unexpected results

### ISSUE THREAD

**Issue by jelmd** [joyent/node#25928]
On Solaris (using 11.3) adding dns.V4MAPPED to dnsopts.hints seems to be not a good idea, since it forces to return _always_ IPv6ified addresses, which is unexpected and let the following tests fail:

```
 === release test-net-better-error-messages-port ===
Path: parallel/test-net-better-error-messages-port
assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: '::ffff:127.0.0.1' == '127.0.0.1'
    at Socket.<anonymous> (/export/scratch/build/node-v5.0.0/test/parallel/test-net-better-error-messages-port.js:13:10)
    at Socket.<anonymous> (/export/scratch/build/node-v5.0.0/test/common.js:371:15)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1255:8)
    at doNTCallback2 (node.js:450:9)
    at process._tickCallback (node.js:364:17)
Command: out/Release/node /export/scratch/build/node-v5.0.0/test/parallel/test-net-better-error-messages-port.js
=== release test-net-dns-lookup ===                                     
Path: parallel/test-net-dns-lookup
assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: '::ffff:127.0.0.1' == '127.0.0.1'
    at Socket.<anonymous> (/export/scratch/build/node-v5.0.0/test/parallel/test-net-dns-lookup.js:15:12)
    at emitThree (events.js:97:13)
    at Socket.emit (events.js:175:7)
    at net.js:968:10
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)
Command: out/Release/node /export/scratch/build/node-v5.0.0/test/parallel/test-net-dns-lookup.js
=== release test-net-remote-address-port ===                                   
Path: parallel/test-net-remote-address-port
assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: -1 != -1
    at Socket.<anonymous> (/export/scratch/build/node-v5.0.0/test/parallel/test-net-remote-address-port.js:35:12)
    at emitNone (events.js:67:13)
    at Socket.emit (events.js:166:7)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1050:10)
Command: out/Release/node /export/scratch/build/node-v5.0.0/test/parallel/test-net-remote-address-port.js
```

Fix: http://iws.cs.uni-magdeburg.de/~elkner/tmp/node5/ipv4.patch

**Comment by ChALkeR** [comment]
[README.md](https://github.com/nodejs/node-v0.x-archive/blob/moved/README.md):

> New issues and pull requests opened here will automatically be rejected.

**Comment by ChALkeR** [comment]
Linking with https://github.com/nodejs/node/issues/3800 for reference.
