### ISSUE TITLE
Problem deploying nodejs app to Heroku

### ISSUE THREAD

**Issue by albo94** [joyent/node#26578]
I developed my app in cloud9 and there it works correctly.
My app is a simple Telegram bot that takes data from a Google Spreadsheet and send them to Telegram.
<img width="198" alt="schermata 2016-08-31 alle 18 20 51" src="https://cloud.githubusercontent.com/assets/20287100/18137211/bbd41376-6fa7-11e6-86bb-dfa5a6ff7e76.png">
Now I'd like to deploy it to Heroku but I obtain this log:

2016-08-31T10:32:59.512579+00:00 app[web.1]: 
2016-08-31T10:32:59.512582+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2016-08-31T10:32:59.512583+00:00 app[web.1]: npm ERR! /app/npm-debug.log
2016-08-31T10:33:01.187496+00:00 heroku[web.1]: Starting process with command npm start
2016-08-31T10:33:03.136731+00:00 heroku[web.1]: Process exited with status 1
2016-08-31T10:33:03.153399+00:00 heroku[web.1]: State changed from starting to crashed
2016-08-31T10:33:02.998453+00:00 app[web.1]: 
2016-08-31T10:33:02.998470+00:00 app[web.1]: > @ start /app
2016-08-31T10:33:02.998470+00:00 app[web.1]: > node server.js
2016-08-31T10:33:02.998471+00:00 app[web.1]: 
2016-08-31T10:33:03.058748+00:00 app[web.1]: module.js:341
2016-08-31T10:33:03.058751+00:00 app[web.1]: throw err;
2016-08-31T10:33:03.058751+00:00 app[web.1]: ^
2016-08-31T10:33:03.058752+00:00 app[web.1]: 
2016-08-31T10:33:03.058752+00:00 app[web.1]: Error: Cannot find module 'node-telegram-bot-api'
2016-08-31T10:33:03.058753+00:00 app[web.1]: at Function.Module._resolveFilename (module.js:339:15)
2016-08-31T10:33:03.058755+00:00 app[web.1]: at Function.Module._load (module.js:290:25)
2016-08-31T10:33:03.058756+00:00 app[web.1]: at Module.require (module.js:367:17)
2016-08-31T10:33:03.058756+00:00 app[web.1]: at require (internal/module.js:20:19)
2016-08-31T10:33:03.058759+00:00 app[web.1]: at Function.Module.runMain (module.js:447:10)
2016-08-31T10:33:03.058758+00:00 app[web.1]: at Function.Module._load (module.js:314:12)
2016-08-31T10:33:03.065092+00:00 app[web.1]: 
2016-08-31T10:33:03.058757+00:00 app[web.1]: at Module._compile (module.js:413:34)
2016-08-31T10:33:03.058757+00:00 app[web.1]: at Object.Module._extensions..js (module.js:422:10)
2016-08-31T10:33:03.058757+00:00 app[web.1]: at Module.load (module.js:357:32)
2016-08-31T10:33:03.058756+00:00 app[web.1]: at Object. (/app/server.js:1:81)
2016-08-31T10:33:03.071742+00:00 app[web.1]: npm ERR! Linux 3.13.0-91-generic
2016-08-31T10:33:03.072123+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2016-08-31T10:33:03.072353+00:00 app[web.1]: npm ERR! node v5.11.1
2016-08-31T10:33:03.073367+00:00 app[web.1]: npm ERR! npm v3.8.6
2016-08-31T10:33:03.074109+00:00 app[web.1]: npm ERR! Exit status 1
2016-08-31T10:33:03.073963+00:00 app[web.1]: npm ERR! @ start: node server.js
2016-08-31T10:33:03.074532+00:00 app[web.1]: npm ERR! Failed at the @ start script 'node server.js'.
2016-08-31T10:33:03.074272+00:00 app[web.1]: npm ERR! 
2016-08-31T10:33:03.073730+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2016-08-31T10:33:03.075021+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2016-08-31T10:33:03.075189+00:00 app[web.1]: npm ERR! node server.js
2016-08-31T10:33:03.074584+00:00 app[web.1]: npm ERR! Make sure you have the latest version of node.js and npm installed.
2016-08-31T10:33:03.074731+00:00 app[web.1]: npm ERR! If you do, this is most likely a problem with the package,
2016-08-31T10:33:03.074878+00:00 app[web.1]: npm ERR! not with npm itself.
2016-08-31T10:33:03.075344+00:00 app[web.1]: npm ERR! You can get information on how to open an issue for this project with:
2016-08-31T10:33:03.075502+00:00 app[web.1]: npm ERR! npm bugs 
2016-08-31T10:33:03.075643+00:00 app[web.1]: npm ERR! Or if that isn't available, you can get their info via:
2016-08-31T10:33:03.075788+00:00 app[web.1]: npm ERR! npm owner ls 
2016-08-31T10:33:03.075928+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2016-08-31T10:33:03.079218+00:00 app[web.1]: 
2016-08-31T10:33:03.079417+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2016-08-31T10:33:03.079553+00:00 app[web.1]: npm ERR! /app/npm-debug.log
2016-08-31T10:33:05.299997+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=ambulanza.herokuapp.com request_id=e6fd68ab-f06e-4863-b205-5ce057ac2270 fwd="130.211.64.181" dyno= connect= service= status=503 bytes=
2016-08-31T10:36:46.214435+00:00 heroku[api]: Deploy 3583303 by alberto.grigis@gmail.com
2016-08-31T10:36:46.214435+00:00 heroku[api]: Release v6 created by alberto.grigis@gmail.com
2016-08-31T10:36:46.410887+00:00 heroku[slug-compiler]: Slug compilation started
2016-08-31T10:36:46.410892+00:00 heroku[slug-compiler]: Slug compilation finished
2016-08-31T10:36:46.806101+00:00 heroku[web.1]: State changed from crashed to starting
2016-08-31T10:36:48.269803+00:00 heroku[web.1]: Starting process with command npm start
2016-08-31T10:36:50.800668+00:00 heroku[web.1]: Process exited with status 1
2016-08-31T10:36:50.809850+00:00 heroku[web.1]: State changed from starting to crashed
2016-08-31T10:36:50.602991+00:00 app[web.1]: 
2016-08-31T10:36:50.603004+00:00 app[web.1]: > @ start /app
2016-08-31T10:36:50.603005+00:00 app[web.1]: > node server.js
2016-08-31T10:36:50.603006+00:00 app[web.1]: 
2016-08-31T10:36:50.695481+00:00 app[web.1]: module.js:341
2016-08-31T10:36:50.695483+00:00 app[web.1]: throw err;
2016-08-31T10:36:50.695484+00:00 app[web.1]: ^
2016-08-31T10:36:50.695485+00:00 app[web.1]: 
2016-08-31T10:36:50.695486+00:00 app[web.1]: Error: Cannot find module 'node-telegram-bot-api'
2016-08-31T10:36:50.695486+00:00 app[web.1]: at Function.Module._resolveFilename (module.js:339:15)
2016-08-31T10:36:50.695487+00:00 app[web.1]: at Function.Module._load (module.js:290:25)
2016-08-31T10:36:50.695488+00:00 app[web.1]: at Module.require (module.js:367:17)
2016-08-31T10:36:50.695488+00:00 app[web.1]: at require (internal/module.js:20:19)
2016-08-31T10:36:50.695489+00:00 app[web.1]: at Object. (/app/server.js:1:81)
2016-08-31T10:36:50.695490+00:00 app[web.1]: at Module._compile (module.js:413:34)
2016-08-31T10:36:50.695490+00:00 app[web.1]: at Object.Module._extensions..js (module.js:422:10)
2016-08-31T10:36:50.695491+00:00 app[web.1]: at Module.load (module.js:357:32)
2016-08-31T10:36:50.695492+00:00 app[web.1]: at Function.Module._load (module.js:314:12)
2016-08-31T10:36:50.695496+00:00 app[web.1]: at Function.Module.runMain (module.js:447:10)
2016-08-31T10:36:50.702924+00:00 app[web.1]: 
2016-08-31T10:36:50.710366+00:00 app[web.1]: npm ERR! Linux 3.13.0-93-generic
2016-08-31T10:36:50.710745+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2016-08-31T10:36:50.710989+00:00 app[web.1]: npm ERR! node v5.11.1
2016-08-31T10:36:50.712030+00:00 app[web.1]: npm ERR! npm v3.8.6
2016-08-31T10:36:50.712239+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2016-08-31T10:36:50.712430+00:00 app[web.1]: npm ERR! @ start: node server.js
2016-08-31T10:36:50.712625+00:00 app[web.1]: npm ERR! Exit status 1
2016-08-31T10:36:50.712810+00:00 app[web.1]: npm ERR! 
2016-08-31T10:36:50.713277+00:00 app[web.1]: npm ERR! If you do, this is most likely a problem with the package,
2016-08-31T10:36:50.712966+00:00 app[web.1]: npm ERR! Failed at the @ start script 'node server.js'.
2016-08-31T10:36:50.713426+00:00 app[web.1]: npm ERR! not with npm itself.
2016-08-31T10:36:50.713574+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2016-08-31T10:36:50.713125+00:00 app[web.1]: npm ERR! Make sure you have the latest version of node.js and npm installed.
2016-08-31T10:36:50.713734+00:00 app[web.1]: npm ERR! node server.js
2016-08-31T10:36:50.713884+00:00 app[web.1]: npm ERR! You can get information on how to open an issue for this project with:
2016-08-31T10:36:50.714034+00:00 app[web.1]: npm ERR! npm bugs 
2016-08-31T10:36:50.714396+00:00 app[web.1]: npm ERR! Or if that isn't available, you can get their info via:
2016-08-31T10:36:50.714398+00:00 app[web.1]: npm ERR! npm owner ls 
2016-08-31T10:36:50.714398+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2016-08-31T10:36:50.717523+00:00 app[web.1]: 
2016-08-31T10:36:50.717761+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2016-08-31T10:36:50.717907+00:00 app[web.1]: npm ERR! /app/npm-debug.log
2016-08-31T10:36:54.720441+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=ambulanza.herokuapp.com request_id=f8ff1465-d3be-4069-8430-7f8e8c28b1d2 fwd="130.211.64.181" dyno= connect= service= status=503 bytes=
2016-08-31T10:39:25.169099+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=ambulanza.herokuapp.com request_id=5d6bde9e-3ccf-4d47-b866-c463764bf2a6 fwd="130.211.64.181" dyno= connect= service= status=503 bytes=

Can anyone help me?
Thank you very much

Alberto

**Comment by cjihrig** [comment]
This issue tracker is abandoned in favor of https://github.com/nodejs/node. However, for general support questions like this, please try https://github.com/nodejs/help.

**Comment by TheDiamondYT1** [comment]
Does nobody read the README anymore!?
