### ISSUE TITLE
neo4j Error: getaddrinfo ENOENT localhost:7474   

### ISSUE THREAD

**Issue by jenevaL** [joyent/node#26589]
how can I fix this error?

C:\neo4j>node app.js
Server Started on port 3000
GET / 200 919.752 ms - 107
{ Error: getaddrinfo ENOENT localhost:7474
    at Neo4jError.Error (native)
    at new Neo4jError (C:\neo4j\node_modules\neo4j-driver\lib\v1\error.js:65:132)
    at newError (C:\neo4j\node_modules\neo4j-driver\lib\v1\error.js:55:10)
    at NodeChannel._handleConnectionError (C:\neo4j\node_modules\neo4j-driver\lib\v1\internal\ch-node.js:322:41)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1022:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) code: 'SessionExpired' }
GET /favicon.ico 404 33.895 ms - 24

**Comment by eljefedelrodeodeljefe** [comment]
That is likely not an issue with node itself
