### ISSUE TITLE
test: gc/test-net-timeout fails consistently

### ISSUE THREAD

**Issue by bnoordhuis** [joyent/node#4176]
```
Done: 500/500
Collected: 499/500
All should be collected now.
Collected: 499/500
timers.js:102
            if (!process.listeners('uncaughtException').length) throw e;
                                                                      ^
AssertionError: false == true
    at null._onTimeout (/home/bnoordhuis/src/nodejs/master/test/gc/test-net-timeout.js:64:7)
    at Timer.list.ontimeout (timers.js:100:19)
    at process._makeCallback (node.js:248:20)
Command: out/Release/node --expose-gc /home/bnoordhuis/src/nodejs/master/test/gc/test-net-timeout.js
```

/cc @isaacs?

**Comment by jasnell** [comment]
@bnoordhuis ... I assume this is resolved?

**Comment by bnoordhuis** [comment]
I guess so.  I hope so!  Closing.
