### ISSUE TITLE
Querystring throws an excpetion

### ISSUE THREAD

**Issue by davidmurdoch** [joyent/node#4247]
```javascript
var url = require("url.js");
var href = "/?%ED%A1%BC";
var parsed = url.parse( href , true ) );

// 1:   URIError: URI malformed
//     at encodeURIComponent (native)
//     at Object.QueryString.escape (querystring.js:114:10)
//     at QueryString.stringify.QueryString.encode (querystring.js:143:28)
//     at Array.map (native)
//     at Object.QueryString.stringify.QueryString.encode (querystring.js:142:29)
//     at urlFormat (url.js:348:25)
//     at Object.urlParse [as parse] (url.js:310:14)
```
`QueryString.parse` is careful to `try/catch` `decodeURIComponent` but `QueryString.stringify` just goes for `encodeURIComponent` all willy nilly.

Perhaps an `QueryString.escapeBuffer` is needed?

**Comment by jasnell** [comment]
Cannot reproduce failure under v0.12.3. 
@davidmurdoch ... what version of node were you using? Is this still an issue. Can reopen with new information
