### ISSUE TITLE
node can't run files with newlines in their filenames

### ISSUE THREAD

**Issue by benatkin** [joyent/node#4779]
Should `node` be able to be run on files anytime `cat` can be run on them? This is node v0.8.6 on Mac OS X Lion.

```
bmamba:~ bat$ echo 'console.log("Hello, world.");' > 'my
> file
> name'
bmamba:~ bat$ cat 'my
> file
> name'
console.log("Hello, world.");
bmamba:~ bat$ ls my*
my?file?name
bmamba:~ bat$ node 'my
> file
> name'

fs.js:520
  return binding.lstat(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory '/Users/bat/name'
    at Object.fs.lstatSync (fs.js:520:18)
    at Object.realpathSync (fs.js:1044:21)
    at tryFile (module.js:142:15)
    at Function.Module._findPath (module.js:181:18)
    at Function.Module._resolveFilename (module.js:336:25)
    at Function.Module._load (module.js:280:25)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
bmamba:~ bat$
```

I typed C-j to get the newlines, but return works too if you're in quotes.

**Comment by jasnell** [comment]
Going to close this due to lack of activity and priority. While node does hiccup on filenames with new lines in them, it's generally not an issue in practice. io.js appears to have the same issue. If someone does wish to pursue this, then a PR to either nodejs/io.js or nodejs/node would be best.
