### ISSUE TITLE
TypeError: Proxy handler #<Object> has no 'getOwnPropertyNames' trap

### ISSUE THREAD

**Issue by hemanth** [joyent/node#6126]
Was expecting `tab-completion` on `random.v<tab>` got the below, on `v0.11.2` with `--use-strict --harmony --harmony-generators`

```javascript
>  var random = Proxy.create({get: function() {return Math.random();}});

random.vTypeError: Proxy handler #<Object> has no 'getOwnPropertyNames' trap
    at Function.getOwnPropertyNames (native)
    at repl.js:585:40
    at REPLServer.defaultEval (repl.js:128:7)
    at REPLServer.b [as eval] (domain.js:183:18)
    at REPLServer.complete (repl.js:580:14)
    at Interface.complete [as completer] (repl.js:166:10)
    at Interface._tabComplete (readline.js:352:8)
    at Interface._ttyWrite (readline.js:811:14)
    at ReadStream.onkeypress (readline.js:99:10)
    at ReadStream.EventEmitter.emit (events.js:100:17)
```
Noticed `0.11.6` hmm yet to try on that!

**Comment by jasnell** [comment]
Assuming no longer relevant. @joyent/node-coreteam

**Comment by misterdjules** [comment]
@jasnell It seems it's still relevant. Proxies were moved behind the `--harmony-proxies` flag and I can reproduce the problem as reported using this flag:
```
➜  v0.12 git:(v0.12) ✗ ./node --use-strict --harmony --harmony-generators --harmony-proxies
> var random = Proxy.create({get: function() {return Math.random();}});
undefined
> random.vTypeError: Proxy handler #<Object> has no 'getOwnPropertyNames' trap
    at Function.getOwnPropertyNames (native)
    at repl.js:604:40
    at REPLServer.defaultEval (repl.js:147:5)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.complete (repl.js:599:14)
    at REPLServer.complete [as completer] (repl.js:185:10)
    at REPLServer.Interface._tabComplete (readline.js:381:8)
    at REPLServer.Interface._ttyWrite (readline.js:849:14)
    at ReadStream.onkeypress (readline.js:109:10)
> random.v                                                                                                                                                                                                                                               ➜  v0.12 git:(v0.12) ✗ ./node --version
v0.12.5-pre
➜  v0.12 git:(v0.12) ✗
```
Reopening, but please feel free to close it if I'm wrong. Thanks!
