### ISSUE TITLE
problems executing node script by unc path [windows]

### ISSUE THREAD

**Issue by adrai** [joyent/node#6260]
```node.js
require('fs').readdirSync(__dirname + '/subfolder');
```

and executing it in this way:

    node "D:\tmp\test.js"

it works.

but executing with unc path:

    node "\\?\D:\tmp\test.js"

results with this error:

    fs.js:654
      return binding.readdir(pathModule._makeLong(path));
                     ^
    Error: ENOENT, no such file or directory 'D:\tmp/subfolder'
        at Object.fs.readdirSync (fs.js:654:18)
        at Object.<anonymous> (\\?\D:\tmp\test.js:1:77)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Function.Module.runMain (module.js:497:10)
        at startup (node.js:119:16)
        at node.js:901:3

**Comment by mk-pmb** [comment]
Seems to be a bug in the connect module then.

**Comment by adrai** [comment]
ohhh.... this is old... we can close this...
