### ISSUE TITLE
v0.10.22 + v0.11.9-15-g5ce4eed both fail make test with same failures

### ISSUE THREAD

**Issue by davidfavor** [joyent/node#6600]
```
/usr/bin/python tools/test.py --mode=release simple message
=== release test-child-process-stdio-big-write-end ===                    
Path: simple/test-child-process-stdio-big-write-end
Command: out/Release/node /smartbuild/work/node-v0.10.22/test/simple/test-child-process-stdio-big-write-end.js
--- TIMEOUT ---
=== release test-http-curl-chunk-problem ===                                   
Path: simple/test-http-curl-chunk-problem
dd command:  dd if=/dev/zero of="/smartbuild/work/node-v0.10.22/test/tmp/big" bs=1024 count=10240
Server running at http://localhost:8080
making curl request
assert.js:92
  throw new assert.AssertionError({
        ^
AssertionError: "8c206a1a87599f532ce68675536f0b1546900d7a" == "2bccbd2f38f15c13eb7d5a89fd9d85f595e23bc3"
    at /smartbuild/work/node-v0.10.22/test/simple/test-http-curl-chunk-problem.js:44:12
    at ChildProcess.exithandler (child_process.js:635:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:735:16)
    at Socket.<anonymous> (child_process.js:948:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
Command: out/Release/node /smartbuild/work/node-v0.10.22/test/simple/test-http-curl-chunk-problem.js
```

**Comment by jasnell** [comment]
Does not appear to be relevant any longer. Can reopen if necessary.
