### ISSUE TITLE
Node is randomly hanging 

### ISSUE THREAD

**Issue by goelvivek** [joyent/node#6643]
Hi , I am using node-gcm module. 
I am facing a random hang problem with node. Following warning is getting logged in stderr 

```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
at EventEmitter.addListener (events.js:160:15)
at Readable.on (_stream_readable.js:689:33)
at ClientRequest. (/node/node_modules/node-gcm/lib/sender.js:94:16)
at EventEmitter.emit (events.js:117:20)
at http.js:1759:9
at process._tickDomainCallback (node.js:459:13)
---------------------------------------------
at Sender.sendNoRetry (node/node_modules/node-gcm/lib/sender.js:92:14)
at Sender.send (src/my_modules/notification/lib/client/android/index.js:19:22)
```

And process is getting hanged

**Comment by jasnell** [comment]
@goelvivek ... I know it's been a while, but is this still an issue for you? I assume we can safely close this?

**Comment by goelvivek** [comment]
I think we can close this issue for now. As currently I don't have
reproducible test case.
