### ISSUE TITLE
ENOENT for piped output

### ISSUE THREAD

**Issue by Queuecumber** [joyent/node#7488]
When running the following command 

    coffeelint -f <( echo $COFFEELINT_SETTINGS ) .

The following error is reported:

    fs.js:679
    return binding.lstat(pathModule._makeLong(path));
                 ^
    Error: ENOENT, no such file or directory '/proc/21512/fd/pipe:[140746056]'
      at Object.fs.lstatSync (fs.js:679:18)
      at Object.realpathSync (fs.js:1267:21)
      at read (/usr/lib/node_modules/coffeelint/lib/commandline.js:35:19)
      at Object.<anonymous> (/usr/lib/node_modules/coffeelint/lib/commandline.js:447:29)
      at Object.<anonymous> (/usr/lib/node_modules/coffeelint/lib/commandline.js:476:4)
      at Module._compile (module.js:456:26)
      at Object.Module._extensions..js (module.js:474:10)
      at Module.load (module.js:356:32)
      at Function.Module._load (module.js:312:12)
      at Module.require (module.js:364:17)
      at require (module.js:380:17)
      at Object.<anonymous> (/usr/lib/node_modules/coffeelint/bin/coffeelint:17:5)
      at Module._compile (module.js:456:26)
      at Object.Module._extensions..js (module.js:474:10)
      at Module.load (module.js:356:32)
      at Function.Module._load (module.js:312:12)
      at Function.Module.runMain (module.js:497:10)
      at startup (node.js:119:16)
      at node.js:902:3

Which appears to be an error with the way node is handling these piped files.
Let me know if I can provide more information, this is happening on Ubuntu Linux but would effect anyone running bash.

**Comment by jasnell** [comment]
@Queuecumber ... I know it's been a while but is this still an issue for you?

**Comment by Queuecumber** [comment]
I don't know, I stopped using coffeescript and therefore coffeelint. I can try to test it if I find time

**Comment by jasnell** [comment]
Closing for now. Can reopen if necessary.
