### ISSUE TITLE
util: inspect() throws TypeError on proxy objects

### ISSUE THREAD

**Issue by bnoordhuis** [joyent/node#7539]
```
$ out/Debug/node --harmony -p 'Proxy.create({}, {})'
util.js:216
      isFunction(value.inspect) &&
                      ^
TypeError: undefined is not a function
    at formatValue (util.js:216:23)
    at inspect (util.js:147:10)
    at Console.exports.format (util.js:27:20)
    at Console.log (console.js:53:34)
    at evalScript (node.js:429:38)
    at startup (node.js:85:7)
    at node.js:807:3
```

It also doesn't like certain kinds of 'magical' objects:

```
$ out/Debug/node --expose_debug_as=D -p D.builtins
util.js:235
  var keys = Object.keys(value);
                    ^
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at formatValue (util.js:235:21)
    at formatProperty (util.js:450:15)
    at util.js:360:14
    at Array.map (native)
    at formatValue (util.js:359:19)
    at inspect (util.js:147:10)
    at Console.exports.format (util.js:27:20)
    at Console.log (console.js:53:34)
    at evalScript (node.js:429:38)
```

Maybe it's because D.builtins is a recursive structure but util.format() is supposed to handle those, right?

Verified with today's master, commit 26a1b71.

**Comment by jasnell** [comment]
Proxy is no more. It has ceased to be. It's gone off to meet it's maker.
