### ISSUE TITLE
test: pummel/test-vm-memleak fails

### ISSUE THREAD

**Issue by bnoordhuis** [joyent/node#7664]
This test did pass in the past but now it doesn't.  Haven't bisected it but as a heads up:
 
```
$ python tools/test.py pummel/test-vm-memleak
=== release test-vm-memleak ===                    
Path: pummel/test-vm-memleak
evalmachine.<anonymous>:1
throw 1;
^
max mem: 97mb
AssertionError: false == true
    at process.<anonymous> (/home/bnoordhuis/src/master/test/pummel/test-vm-memleak.js:54:10)
    at process.EventEmitter.emit (events.js:129:20)
Command: out/Release/node /home/bnoordhuis/src/master/test/pummel/test-vm-memleak.js
[00:06|% 100|+   0|-   1]: Done                   
```

Not sure why it's using almost twice the expected memory.

**Comment by jasnell** [comment]
@bnoordhuis ... is this still an issue for you?

**Comment by bnoordhuis** [comment]
IIRC, I fixed that in https://github.com/iojs/io.js/pull/280.

**Comment by jasnell** [comment]
Closing then. We can backport if appropriate or pick up in the converged stream
