### ISSUE TITLE
Sometimes duplicate request handle  calls

### ISSUE THREAD

**Issue by mogadanez** [joyent/node#8262]
Multipart POST request( file upload) more often to reproduce with small files.

I receive 2 callbacks in request handle, and duplicate files.

```
Trace: OMG 156 1409056984176
    at Server.app (/home/apopov/projects/test/node_modules/express/node_modules/connect/lib/connect.js:67:15)
    at Server.emit (events.js:98:17)
    at HTTPParser.parser.onIncoming (http.js:2108:12)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
    at Socket.socket.ondata (http.js:1966:22)
    at TCP.onread (net.js:527:27)
```

```
Trace: OMG 160 1409056984262
    at Server.app (/home/apopov/projects/test/node_modules/express/node_modules/connect/lib/connect.js:67:15)
    at Server.emit (events.js:98:17)
    at HTTPParser.parser.onIncoming (http.js:2108:12)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
    at Socket.socket.ondata (http.js:1966:22)
    at TCP.onread (net.js:527:27)
```
156  and 160 is  req.socket._handle.fd, sometimes its different sometimes same.
I'm pretty sure  that client side send only 1 request( I make it with curl ). So i'm very stucked from where second  handler was happens.

```
NET: 27131 onconnection
NET: 27131 _read
NET: 27131 Socket._read readStart
NET: 27131 onread EOF 782832 636 783468
NET: 27131 got data
NET: 27131 afterWrite 0 { domain: 
   { domain: null,
     _events: { error: [Function] },
     _maxListeners: 10,
     members: [ [Object], [Object] ] },
  bytes: 303,
  oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 onread EOF 783472 628 784100
NET: 27131 got data
NET: 27131 afterWrite 0 { domain: 
   { domain: null,
     _events: { error: [Function] },
     _maxListeners: 10,
     members: [ [Object], [Object] ] },
  bytes: 303,
  oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 onread EOF 784112 647 784759
NET: 27131 got data
NET: 27131 connect: find host localhost
NET: 27131 afterConnect
NET: 27131 _read
NET: 27131 Socket._read readStart
NET: 27131 afterWrite 0 { domain: 
   { domain: null,
     _events: { error: [Function] },
     _maxListeners: 10,
     members: [ [Object], [Object] ] },
  bytes: 176,
  oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 onread EOF 784768 775 785543
NET: 27131 got data
NET: 27131 connect: find host localhost
NET: 27131 destroy undefined
NET: 27131 destroy
NET: 27131 close
NET: 27131 close handle
NET: 27131 emit close
NET: 27131 afterConnect
NET: 27131 _read
NET: 27131 Socket._read readStart
NET: 27131 afterWrite 0 { domain: 
   { domain: null,
     _events: { error: [Function] },
     _maxListeners: 10,
     members: [ [Object], [Object] ] },
  bytes: 195,
  oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 onconnection
NET: 27131 _read
NET: 27131 Socket._read readStart
NET: 27131 onread EOF 785552 629 786181
NET: 27131 got data
NET: 27131 afterWrite 0 { domain: 
   { domain: null,
     _events: { error: [Function] },
     _maxListeners: 10,
     members: [ [Object], [Object] ] },
  bytes: 303,
  oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 onread EOF 786192 198 786390
NET: 27131 got data
NET: 27131 onread EOF 786400 45 786445
NET: 27131 got data
NET: 27131 destroy undefined
NET: 27131 destroy
NET: 27131 close
NET: 27131 close handle
NET: 27131 emit close
NET: 27131 afterWrite 0 { domain: 
   { domain: null,
     _events: { error: [Function] },
     _maxListeners: 10,
     members: [ [Object], [Object] ] },
  bytes: 52,
  oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 onread EOF 786448 318 786766
NET: 27131 got data
NET: 27131 _read
NET: 27131 afterWrite 0 { bytes: 58, oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 onread EOF 786768 135 786903
NET: 27131 got data
NET: 27131 _read
NET: 27131 afterWrite 0 { bytes: 297, oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 onread EOF 786912 432 787344
NET: 27131 got data
NET: 27131 afterWrite 0 { bytes: 246, oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 onread EOF 787344 626 787970
NET: 27131 got data
NET: 27131 afterWrite 0 { domain: 
   { domain: null,
     _events: { error: [Function] },
     _maxListeners: 10,
     members: [ [Object], [Object] ] },
  bytes: 303,
  oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 onread EOF 787984 551 788535
NET: 27131 got data
NET: 27131 connect: find host localhost
NET: 27131 afterConnect
NET: 27131 _read
NET: 27131 Socket._read readStart
NET: 27131 afterWrite 0 { domain: 
   { domain: null,
     _events: { error: [Function] },
     _maxListeners: 10,
     members: [ [Object], [Object] ] },
  bytes: 176,
  oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 onread EOF 788544 775 789319
NET: 27131 got data
NET: 27131 connect: find host localhost
NET: 27131 destroy undefined
NET: 27131 destroy
NET: 27131 close
NET: 27131 close handle
NET: 27131 emit close
NET: 27131 onread EOF 789328 654 789982
NET: 27131 got data
NET: 27131 onconnection
NET: 27131 _read
NET: 27131 Socket._read readStart
NET: 27131 onconnection
NET: 27131 _read
NET: 27131 Socket._read readStart
NET: 27131 onconnection
NET: 27131 _read
NET: 27131 Socket._read readStart
NET: 27131 onconnection
NET: 27131 _read
NET: 27131 Socket._read readStart
NET: 27131 afterConnect
NET: 27131 _read
NET: 27131 Socket._read readStart
NET: 27131 onread EOF 789984 630 790614
NET: 27131 got data
NET: 27131 onread EOF 790624 661 791285
NET: 27131 got data
NET: 27131 onread EOF 791296 630 791926
NET: 27131 got data
NET: 27131 onread EOF 791936 643 792579
NET: 27131 got data
NET: 27131 afterWrite 0 { domain: 
   { domain: null,
     _events: { error: [Function] },
     _maxListeners: 10,
     members: [ [Object], [Object] ] },
  bytes: 303,
  oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 afterWrite 0 { domain: 
   { domain: null,
     _events: { error: [Function] },
     _maxListeners: 10,
     members: [ [Object], [Object] ] },
  bytes: 195,
  oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 onread EOF 792592 654 793246
NET: 27131 got data
NET: 27131 afterWrite 0 { domain: 
   { domain: null,
     _events: { error: [Function] },
     _maxListeners: 10,
     members: [ [Object], [Object] ] },
  bytes: 303,
  oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 afterWrite 0 { domain: 
   { domain: null,
     _events: { error: [Function] },
     _maxListeners: 10,
     members: [ [Object], [Object] ] },
  bytes: 303,
  oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 afterWrite 0 { domain: 
   { domain: null,
     _events: { error: [Function] },
     _maxListeners: 10,
     members: [ [Object], [Object] ] },
  bytes: 303,
  oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 onread EOF 793248 647 793895
NET: 27131 got data
NET: 27131 connect: find host localhost
NET: 27131 afterWrite 0 { domain: 
   { domain: null,
     _events: { error: [Function] },
     _maxListeners: 10,
     members: [ [Object], [Object] ] },
  bytes: 303,
  oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 afterWrite 0 { domain: 
   { domain: null,
     _events: { error: [Function] },
     _maxListeners: 10,
     members: [ [Object], [Object] ] },
  bytes: 303,
  oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 afterConnect
NET: 27131 _read
NET: 27131 Socket._read readStart
NET: 27131 afterWrite 0 { domain: 
   { domain: null,
     _events: { error: [Function] },
     _maxListeners: 10,
     members: [ [Object], [Object] ] },
  bytes: 176,
  oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 onread EOF 793904 826 794730
NET: 27131 got data
NET: 27131 connect: find host localhost
NET: 27131 onread EOF 794736 775 795511
NET: 27131 got data
NET: 27131 connect: find host localhost
NET: 27131 destroy undefined
NET: 27131 destroy
NET: 27131 close
NET: 27131 close handle
NET: 27131 emit close
NET: 27131 destroy undefined
NET: 27131 destroy
NET: 27131 close
NET: 27131 close handle
NET: 27131 has server
NET: 27131 SERVER _emitCloseIfDrained
NET: 27131 SERVER handle? true   connections? 5
NET: 27131 onread EOF 795520 647 796167
NET: 27131 got data
NET: 27131 emit close
NET: 27131 onread EOF 796176 551 796727
NET: 27131 got data
NET: 27131 connect: find host localhost
NET: 27131 afterConnect
NET: 27131 _read
NET: 27131 Socket._read readStart
NET: 27131 afterConnect
NET: 27131 _read
NET: 27131 Socket._read readStart
NET: 27131 afterWrite 0 { domain: 
   { domain: null,
     _events: { error: [Function] },
     _maxListeners: 10,
     members: [ [Object], [Object] ] },
  bytes: 176,
  oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 afterWrite 0 { domain: 
   { domain: null,
     _events: { error: [Function] },
     _maxListeners: 10,
     members: [ [Object], [Object] ] },
  bytes: 195,
  oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 afterWrite 0 { domain: 
   { domain: null,
     _events: { error: [Function] },
     _maxListeners: 10,
     members: [ [Object], [Object] ] },
  bytes: 303,
  oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 afterConnect
NET: 27131 _read
NET: 27131 Socket._read readStart
NET: 27131 afterWrite 0 { domain: 
   { domain: null,
     _events: { error: [Function] },
     _maxListeners: 10,
     members: [ [Object], [Object] ] },
  bytes: 176,
  oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 destroy undefined
NET: 27131 destroy
NET: 27131 already destroyed, fire error callbacks
NET: 27131 onread EOF 796736 479 797215
NET: 27131 got data
NET: 27131 onread EOF 797216 296 797512
NET: 27131 got data
NET: 27131 destroy undefined
NET: 27131 destroy
NET: 27131 close
NET: 27131 close handle
NET: 27131 connect: find host localhost
NET: 27131 emit close
NET: 27131 afterConnect
NET: 27131 _read
NET: 27131 Socket._read readStart
NET: 27131 afterWrite 0 { domain: 
   { domain: null,
     _events: { error: [Function] },
     _maxListeners: 10,
     members: [ [Object], [Object] ] },
  bytes: 195,
  oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 onread EOF 797520 775 798295
NET: 27131 got data
NET: 27131 connect: find host localhost
NET: 27131 destroy undefined
NET: 27131 destroy
NET: 27131 close
NET: 27131 close handle
NET: 27131 emit close
NET: 27131 onread EOF 798304 1463 799767
NET: 27131 got data
Trace: OMG 156 1409056984176
    at Server.app (/home/apopov/projects/test/node_modules/express/node_modules/connect/lib/connect.js:67:15)
    at Server.emit (events.js:98:17)
    at HTTPParser.parser.onIncoming (http.js:2108:12)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
    at Socket.socket.ondata (http.js:1966:22)
    at TCP.onread (net.js:527:27)
NET: 27131 connect: find host localhost
NET: 27131 afterConnect
NET: 27131 _read
NET: 27131 Socket._read readStart
NET: 27131 afterWrite 0 { domain: 
   { domain: null,
     _events: { error: [Function] },
     _maxListeners: 10,
     members: [ [Object], [Object] ] },
  bytes: 195,
  oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 afterConnect
NET: 27131 _read
NET: 27131 Socket._read readStart
NET: 27131 afterWrite 0 { domain: 
   { domain: null,
     _events: { error: [Function] },
     _maxListeners: 10,
     members: [ [Object], [Object] ] },
  bytes: 176,
  oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 destroy undefined
NET: 27131 destroy
NET: 27131 close
NET: 27131 close handle
NET: 27131 has server
NET: 27131 SERVER _emitCloseIfDrained
NET: 27131 SERVER handle? true   connections? 4
NET: 27131 emit close
NET: 27131 onread EOF 799776 826 800602
NET: 27131 got data
NET: 27131 connect: find host localhost
NET: 27131 afterConnect
NET: 27131 _read
NET: 27131 Socket._read readStart
NET: 27131 afterWrite 0 { domain: 
   { domain: null,
     _events: { error: [Function] },
     _maxListeners: 10,
     members: [ [Object], [Object] ] },
  bytes: 176,
  oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 destroy undefined
NET: 27131 destroy
NET: 27131 already destroyed, fire error callbacks
NET: 27131 onread EOF 800608 243 800851
NET: 27131 got data
NET: 27131 destroy undefined
NET: 27131 destroy
NET: 27131 close
NET: 27131 close handle
NET: 27131 emit close
NET: 27131 afterWrite 0 { domain: 
   { domain: null,
     _events: { error: [Function] },
     _maxListeners: 10,
     members: [ [Object], [Object] ] },
  bytes: 52,
  oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 onread EOF 800864 318 801182
NET: 27131 got data
NET: 27131 _read
NET: 27131 afterWrite 0 { bytes: 58, oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 onread EOF 801184 135 801319
NET: 27131 got data
NET: 27131 _read
NET: 27131 connect: find host localhost
NET: 27131 connect: find host localhost
NET: 27131 afterConnect
NET: 27131 _read
NET: 27131 Socket._read readStart
NET: 27131 afterConnect
NET: 27131 _read
NET: 27131 Socket._read readStart
NET: 27131 afterWrite 0 { bytes: 180, oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 afterWrite 0 { bytes: 203, oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 onread EOF 801328 174 801502
NET: 27131 got data
NET: 27131 destroy undefined
NET: 27131 destroy
NET: 27131 close
NET: 27131 close handle
NET: 27131 emit close
NET: 27131 onread EOF 801504 800 802304
NET: 27131 got data
NET: 27131 destroy undefined
NET: 27131 destroy
NET: 27131 close
NET: 27131 close handle
NET: 27131 emit close
NET: 27131 onread EOF 802304 243 802547
NET: 27131 got data
NET: 27131 destroy undefined
NET: 27131 destroy
NET: 27131 close
NET: 27131 close handle
NET: 27131 emit close
NET: 27131 afterWrite 0 { domain: 
   { domain: null,
     _events: { error: [Function] },
     _maxListeners: 10,
     members: [ [Object], [Object] ] },
  bytes: 52,
  oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 onread EOF 802560 318 802878
NET: 27131 got data
NET: 27131 _read
NET: 27131 afterWrite 0 { bytes: 58, oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 onread EOF 802880 135 803015
NET: 27131 got data
NET: 27131 _read
NET: 27131 onread EOF 803024 775 803799
NET: 27131 got data
NET: 27131 connect: find host localhost
NET: 27131 destroy undefined
NET: 27131 destroy
NET: 27131 close
NET: 27131 close handle
NET: 27131 emit close
NET: 27131 destroy undefined
NET: 27131 destroy
NET: 27131 already destroyed, fire error callbacks
NET: 27131 afterWrite 0 { bytes: 358, oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 onread EOF 803808 775 804583
NET: 27131 got data
NET: 27131 destroy undefined
NET: 27131 destroy
NET: 27131 close
NET: 27131 close handle
NET: 27131 connect: find host localhost
NET: 27131 emit close
NET: 27131 onread EOF 804592 243 804835
NET: 27131 got data
NET: 27131 destroy undefined
NET: 27131 destroy
NET: 27131 close
NET: 27131 close handle
NET: 27131 afterConnect
NET: 27131 _read
NET: 27131 Socket._read readStart
NET: 27131 emit close
NET: 27131 afterWrite 0 { domain: 
   { domain: null,
     _events: { error: [Function] },
     _maxListeners: 10,
     members: [ [Object], [Object] ] },
  bytes: 52,
  oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 afterWrite 0 { domain: 
   { domain: null,
     _events: { error: [Function] },
     _maxListeners: 10,
     members: [ [Object], [Object] ] },
  bytes: 195,
  oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 onread EOF 804848 318 805166
NET: 27131 got data
NET: 27131 _read
NET: 27131 afterConnect
NET: 27131 _read
NET: 27131 Socket._read readStart
NET: 27131 afterWrite 0 { bytes: 58, oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 afterWrite 0 { domain: 
   { domain: null,
     _events: { error: [Function] },
     _maxListeners: 10,
     members: [ [Object], [Object] ] },
  bytes: 195,
  oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 onread EOF 805168 135 805303
NET: 27131 got data
NET: 27131 _read
NET: 27131 destroy undefined
NET: 27131 destroy
NET: 27131 already destroyed, fire error callbacks
NET: 27131 afterWrite 0 { bytes: 70, oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 onread EOF 805312 8 805320
NET: 27131 got data
NET: 27131 _read
NET: 27131 connect: find host localhost
NET: 27131 afterConnect
NET: 27131 _read
NET: 27131 Socket._read readStart
NET: 27131 afterWrite 0 { bytes: 181, oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 destroy undefined
NET: 27131 destroy
NET: 27131 close
NET: 27131 close handle
NET: 27131 has server
NET: 27131 SERVER _emitCloseIfDrained
NET: 27131 SERVER handle? true   connections? 3
NET: 27131 destroy undefined
NET: 27131 destroy
NET: 27131 close
NET: 27131 close handle
NET: 27131 has server
NET: 27131 SERVER _emitCloseIfDrained
NET: 27131 SERVER handle? true   connections? 2
NET: 27131 destroy undefined
NET: 27131 destroy
NET: 27131 close
NET: 27131 close handle
NET: 27131 has server
NET: 27131 SERVER _emitCloseIfDrained
NET: 27131 SERVER handle? true   connections? 1
NET: 27131 emit close
NET: 27131 emit close
NET: 27131 emit close
NET: 27131 onconnection
NET: 27131 _read
NET: 27131 Socket._read readStart
NET: 27131 onconnection
NET: 27131 _read
NET: 27131 Socket._read readStart
NET: 27131 onconnection
NET: 27131 _read
NET: 27131 Socket._read readStart
NET: 27131 onread EOF 805328 826 806154
NET: 27131 got data
NET: 27131 connect: find host localhost
NET: 27131 onread EOF 806160 551 806711
NET: 27131 got data
NET: 27131 connect: find host localhost
NET: 27131 onread EOF 806720 647 807367
NET: 27131 got data
NET: 27131 connect: find host localhost
NET: 27131 destroy undefined
NET: 27131 destroy
NET: 27131 close
NET: 27131 close handle
NET: 27131 has server
NET: 27131 SERVER _emitCloseIfDrained
NET: 27131 SERVER handle? true   connections? 3
NET: 27131 destroy undefined
NET: 27131 destroy
NET: 27131 already destroyed, fire error callbacks
NET: 27131 onconnection
NET: 27131 _read
NET: 27131 Socket._read readStart
NET: 27131 onread EOF 807376 193 807569
NET: 27131 got data
NET: 27131 destroy undefined
NET: 27131 destroy
NET: 27131 close
NET: 27131 close handle
NET: 27131 emit close
NET: 27131 emit close
NET: 27131 destroy undefined
NET: 27131 destroy
NET: 27131 already destroyed, fire error callbacks
NET: 27131 afterWrite 0 { bytes: 70, oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 afterConnect
NET: 27131 _read
NET: 27131 Socket._read readStart
NET: 27131 afterConnect
NET: 27131 _read
NET: 27131 Socket._read readStart
NET: 27131 afterConnect
NET: 27131 _read
NET: 27131 Socket._read readStart
NET: 27131 onread EOF 807584 1463 809047
NET: 27131 got data
(/home/apopov/projects/test/node_modules/express/node_modules/connect/lib/connect.js:67:15)
NET: 27131 connect: find host localhost
NET: 27131 destroy undefined
NET: 27131 destroy
NET: 27131 already destroyed, fire error callbacks
NET: 27131 afterWrite 0 { domain: 
   { domain: null,
     _events: { error: [Function] },
     _maxListeners: 10,
     members: [ [Object], [Object] ] },
  bytes: 176,
  oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 afterWrite 0 { domain: 
   { domain: null,
     _events: { error: [Function] },
     _maxListeners: 10,
     members: [ [Object], [Object] ] },
  bytes: 176,
  oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 afterWrite 0 { domain: 
   { domain: null,
     _events: { error: [Function] },
     _maxListeners: 10,
     members: [ [Object], [Object] ] },
  bytes: 176,
  oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 onread EOF 809056 243 809299
NET: 27131 got data
NET: 27131 destroy undefined
NET: 27131 destroy
NET: 27131 close
NET: 27131 close handle
NET: 27131 onread EOF 809312 8 809320
NET: 27131 got data
NET: 27131 _read
NET: 27131 connect: find host localhost
NET: 27131 emit close
NET: 27131 afterWrite 0 { domain: 
   { domain: null,
     _events: { error: [Function] },
     _maxListeners: 10,
     members: [ [Object], [Object] ] },
  bytes: 52,
  oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 onread EOF 809328 318 809646
NET: 27131 got data
NET: 27131 _read
NET: 27131 afterConnect
NET: 27131 _read
NET: 27131 Socket._read readStart
NET: 27131 afterWrite 0 { bytes: 58, oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 afterWrite 0 { domain: 
   { domain: null,
     _events: { error: [Function] },
     _maxListeners: 10,
     members: [ [Object], [Object] ] },
  bytes: 176,
  oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 onread EOF 809648 135 809783
NET: 27131 got data
NET: 27131 _read
NET: 27131 connect: find host localhost
NET: 27131 connect: find host localhost
NET: 27131 afterConnect
NET: 27131 _read
NET: 27131 Socket._read readStart
NET: 27131 afterWrite 0 { bytes: 264, oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 afterWrite 0 { bytes: 1, oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 afterConnect
NET: 27131 _read
NET: 27131 Socket._read readStart
NET: 27131 afterConnect
NET: 27131 _read
NET: 27131 Socket._read readStart
NET: 27131 afterWrite 0 { bytes: 180, oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 afterWrite 0 { bytes: 203, oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 onread EOF 809792 198 809990
NET: 27131 got data
NET: 27131 destroy undefined
NET: 27131 destroy
NET: 27131 already destroyed, fire error callbacks
NET: 27131 destroy undefined
NET: 27131 destroy
NET: 27131 already destroyed, fire error callbacks
NET: 27131 onread EOF 810000 45 810045
NET: 27131 got data
NET: 27131 destroy undefined
NET: 27131 destroy
NET: 27131 close
NET: 27131 close handle
NET: 27131 emit close
NET: 27131 afterWrite 0 { domain: 
   { domain: null,
     _events: { error: [Function] },
     _maxListeners: 10,
     members: [ [Object], [Object] ] },
  bytes: 52,
  oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 onread EOF 810048 318 810366
NET: 27131 got data
NET: 27131 _read
NET: 27131 afterWrite 0 { bytes: 58, oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 onread EOF 810368 135 810503
NET: 27131 got data
NET: 27131 _read
NET: 27131 afterWrite 0 { bytes: 70, oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 onread EOF 810512 12 810524
NET: 27131 got data
NET: 27131 _read
NET: 27131 onread EOF 810528 479 811007
NET: 27131 got data
NET: 27131 onread EOF 811008 296 811304
NET: 27131 got data
NET: 27131 connect: find host localhost
NET: 27131 destroy undefined
NET: 27131 destroy
NET: 27131 close
NET: 27131 close handle
NET: 27131 emit close
NET: 27131 onread EOF 811312 243 811555
NET: 27131 got data
NET: 27131 destroy undefined
NET: 27131 destroy
NET: 27131 close
NET: 27131 close handle
NET: 27131 emit close
NET: 27131 afterWrite 0 { domain: 
   { domain: null,
     _events: { error: [Function] },
     _maxListeners: 10,
     members: [ [Object], [Object] ] },
  bytes: 52,
  oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 onread EOF 811568 318 811886
NET: 27131 got data
NET: 27131 _read
NET: 27131 afterConnect
NET: 27131 _read
NET: 27131 Socket._read readStart
NET: 27131 afterWrite 0 { bytes: 58, oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 afterWrite 0 { domain: 
   { domain: null,
     _events: { error: [Function] },
     _maxListeners: 10,
     members: [ [Object], [Object] ] },
  bytes: 195,
  oncomplete: [Function: afterWrite] }
NET: 27131 afterWrite call cb
NET: 27131 onread EOF 811888 135 812023
NET: 27131 got data
NET: 27131 _read
procceed save File
procceed save File
```

**Comment by jasnell** [comment]
@mogadanez ... are you able to provide a simplified test case to reproduce the issue as requested by @misterdjules ?

**Comment by mogadanez** [comment]
Looks like it somehow depends on third party module https://github.com/expressjs/domain-middleware
After removing this middleware problem disappears

**Comment by jasnell** [comment]
Ok, will close. Can reopen if it does turn out to be a node issue.
