### ISSUE TITLE
EAFNOSUPPORT, address family not supported (getLocalAddresses)

### ISSUE THREAD

**Issue by neophob** [joyent/node#8616]
I'm using docker + qemu and chroot

```
[root@43aae86b85cc tmp]# /usr/bin/node
> var os = require('os');
undefined
> os.networkInterfaces();
Error: EAFNOSUPPORT, address family not supported
    at repl:1:4
    at REPLServer.self.eval (repl.js:110:21)
    at repl.js:249:20
    at REPLServer.self.eval (repl.js:122:7)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
    at Interface._line (readline.js:531:8)
    at Interface._ttyWrite (readline.js:760:14)
    at ReadStream.onkeypress (readline.js:99:10)
```

and a real world issue:
```
[root@43aae86b85cc tmp]# /usr/bin/npm

/usr/lib/node_modules/npm/lib/config/defaults.js:334
  Object.keys(os.networkInterfaces()).map(function (nic) {
                 ^
Error: EAFNOSUPPORT, address family not supported
    at getLocalAddresses (/usr/lib/node_modules/npm/lib/config/defaults.js:334:18)
    at Object.<anonymous> (/usr/lib/node_modules/npm/lib/config/defaults.js:283:23)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/npm/lib/config/core.js:4:18)
    at Module._compile (module.js:456:26)
```

My Network configuration:
```
[root@43aae86b85cc tmp]# ifconfig
eth0: flags=67<UP,BROADCAST,RUNNING>  mtu 1500
        inet 172.17.0.6  netmask 255.255.0.0  broadcast 0.0.0.0
        inet6 fe80::42:acff:fe11:6  prefixlen 64  scopeid 0x20<link>
        ether 02:42:ac:11:00:06  txqueuelen 1000  (Ethernet)
        RX packets 146841  bytes 154892175 (147.7 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 43962  bytes 2392850 (2.2 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 0  (Local Loopback)
        RX packets 12  bytes 928 (928.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 12  bytes 928 (928.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```
any hints how to fix this?

**Comment by borg42** [comment]
@BrianAdams: Our workaround currently is to only install node/npm and our own Bindings (by hand, not through npm) on the embedded board. Everything else currently has to be installed by the user later on.

Which is a bit of a hassle for our users, since you have to buy extra modules to get internet connectivity to the embedded board in question (http://www.tinkerforge.com/en/doc/Hardware/Bricks/RED_Brick.html).

I am no expert in regards to node/npm, so i can't comment on your source code link unfortunately.

**Comment by neophob** [comment]
issue still here with node v0.12

**Comment by techniq** [comment]
FWIW, this doesn't look to be an issue on io.js 1.4.3

```js
root@1a2e02c272cd:/iojs-v1.4.3-linux-armv7l/bin# ./iojs 
> var os = require('os');
undefined
> os.networkInterfaces()
{ lo: 
   [ { address: '127.0.0.1',
       netmask: '255.0.0.0',
       family: 'IPv4',
       mac: '00:00:00:00:00:00',
       internal: true },
     { address: '::1',
       netmask: 'ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff',
       family: 'IPv6',
       mac: '00:00:00:00:00:00',
       scopeid: 0,
       internal: true } ],
  eth0: 
   [ { address: '172.17.0.4',
       netmask: '255.255.0.0',
       family: 'IPv4',
       mac: '02:42:ac:11:00:04',
       internal: false },
     { address: 'fe80::42:acff:fe11:4',
       netmask: 'ffff:ffff:ffff:ffff::',
       family: 'IPv6',
       mac: '02:42:ac:11:00:04',
       scopeid: 9,
       internal: false } ] }
```

**Comment by neophob** [comment]
Tested with io.js v1.6.1:

```
> var os = require('os');
undefined
> os.networkInterfaces()
Error: EAFNOSUPPORT: address family not supported, uv_interface_addresses
    at Error (native)
    at repl:1:4
    at REPLServer.defaultEval (repl.js:124:27)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:277:12)
    at emitOne (events.js:77:13)
    at REPLServer.emit (events.js:166:7)
    at REPLServer.Interface._onLine (readline.js:195:10)
    at REPLServer.Interface._line (readline.js:534:8)
```

**Comment by josephpage** [comment]
:+1: 

```
root@scw-6d4ed6:~# docker run --rm -itv /usr/bin/qemu-x86_64-static:/usr/bin/qemu-x86_64-static google/nodejs npm install gulp

/nodejs/lib/node_modules/npm/node_modules/npmconf/config-defs.js:320
  Object.keys(os.networkInterfaces()).map(function (nic) {
                 ^
Error: EAFNOSUPPORT, address family not supported
    at getLocalAddresses (/nodejs/lib/node_modules/npm/node_modules/npmconf/config-defs.js:320:18)
    at Object.<anonymous> (/nodejs/lib/node_modules/npm/node_modules/npmconf/config-defs.js:268:23)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/nodejs/lib/node_modules/npm/node_modules/npmconf/npmconf.js:4:18)
    at Module._compile (module.js:456:26)
```

**Comment by BrianAdams** [comment]
I can confirm that #8094 fixed this for my qemu case.  Thanks!  I think this issue can be closed now.
