### ISSUE TITLE
Debugging API seems broken in 0.10.34 and 0.10.35

### ISSUE THREAD

**Issue by scharf** [joyent/node#8967]
For some reasons variables cannot be displayed neither in eclipse nor in jetbrains IDEs.

The error message looks something like this:

```
java.lang.RuntimeException: Unsuccessful command ReferenceError: frame_index is not defined
	at org.chromium.sdk.internal.v8native.V8BlockingCallback.messageReceived(V8BlockingCallback.java:22)
	at org.chromium.sdk.internal.v8native.V8Helper$2.messageReceived(V8Helper.java:167)
	at org.chromium.sdk.internal.v8native.V8Helper$2.messageReceived(V8Helper.java:1)
	at org.chromium.sdk.internal.BaseCommandProcessor$3.call(BaseCommandProcessor.java:100)
	at org.chromium.sdk.internal.BaseCommandProcessor$3.call(BaseCommandProcessor.java:1)
	at org.chromium.sdk.internal.BaseCommandProcessor.callThemBack(BaseCommandProcessor.java:134)
	at org.chromium.sdk.internal.BaseCommandProcessor.processIncoming(BaseCommandProcessor.java:104)
	at org.chromium.sdk.internal.v8native.V8CommandProcessor.processIncomingJson(V8CommandProcessor.java:113)
	at org.chromium.sdk.internal.standalonev8.StandaloneVmImpl$4.messageReceived(StandaloneVmImpl.java:115)
	at org.chromium.sdk.internal.transport.SocketConnection$RegularMessageItem.report(SocketConnection.java:120)
	at org.chromium.sdk.internal.transport.SocketConnection$ResponseDispatcherThread.run(SocketConnection.java:209)
```

**Comment by coderaiser** [comment]
Same issue: https://github.com/joyent/node/issues/8948.

**Comment by scharf** [comment]
duplicate of #8948.
