### ISSUE TITLE
simple yeoman generator for angular fails

### ISSUE THREAD

**Issue by ejmolinelli** [joyent/node#8968]
Hey all, I'm trying to learn Angular through Yeoman. I'm not sure if my error is a bower error an npm error or a node.js error so I'm looking for help in all three forums.

I've installed node.js with Homebrew on my mac 10.7, and have successfully installed yeoman (yo), bower and grunt-cli packages with npm.  However, when trying to use my angular generator, the command fails at the same place each time (i've done several iterations of this - uninstalling node, reinstalling, with and without homebrew, to no avail).

```
LSKI1360:bla molinele$ yo angular

     _-----_
    |       |    .--------------------------.
    |--(o)--|    |    Welcome to Yeoman,    |
   `---------´   |   ladies and gentlemen!  |
    ( _´U`_ )    '--------------------------'
    /___A___\    
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

Out of the box I include Bootstrap and some AngularJS recommended modules.

? Would you like to use Sass (with Compass)? No
? Would you like to include Bootstrap? Yes
? Which modules would you like to include? angular-animate.js, angular-cookies.js, angular-resource.js, angular-route.js, angular-sanitize.js, angular-touch.js
   create app/styles/main.css
   create app/index.html
   create bower.json
   create .bowerrc
   create package.json
   create Gruntfile.js
   invoke   angular:common:/usr/local/lib/node_modules/generator-angular/app/index.js
   create     .editorconfig
   create     .gitattributes
   create     .jshintrc
   create     .gitignore
   create     test/.jshintrc
   create     app/.buildignore
   create     app/.htaccess
   create     app/404.html
   create     app/favicon.ico
   create     app/robots.txt
   create     app/views/main.html
   create     app/images/yeoman.png
   invoke   angular:main:/usr/local/lib/node_modules/generator-angular/app/index.js
   create     app/scripts/app.js
   invoke   angular:controller:/usr/local/lib/node_modules/generator-angular/app/index.js
   create     app/scripts/controllers/main.js
   create     test/spec/controllers/main.js
   invoke   karma:app


I'm all done. Running bower install & npm install for you to install the required dependencies. If this fails, try running the command yourself.


   invoke       angular:route
   invoke           angular:controller:/usr/local/lib/node_modules/generator-angular/route/index.js
   create             app/scripts/controllers/about.js
   create             test/spec/controllers/about.js
   invoke           angular:view:/usr/local/lib/node_modules/generator-angular/route/index.js
   create             app/views/about.html
   create     test/karma.conf.js
   create     .travis.yml
npm WARN package.json bla@0.0.0 No description
npm WARN package.json bla@0.0.0 No repository field.
npm WARN package.json bla@0.0.0 No README data
npm WARN package.json bla@0.0.0 No description
npm WARN package.json bla@0.0.0 No repository field.
npm WARN package.json bla@0.0.0 No README data
npm WARN deprecated grunt-ngmin@0.0.3: use grunt-ng-annotate instead
npm WARN deprecated ngmin@0.4.1: use ng-annotate instead
bower angular-resource#1.2.16   cached git://github.com/angular/bower-angular-resource.git#1.2.16
bower angular-resource#1.2.16 validate 1.2.16 against git://github.com/angular/bower-angular-resource.git#1.2.16
bower angular-mocks#1.2.16      cached git://github.com/angular/bower-angular-mocks.git#1.2.16
bower angular-mocks#1.2.16    validate 1.2.16 against git://github.com/angular/bower-angular-mocks.git#1.2.16
bower angular-animate#1.2.16    cached git://github.com/angular/bower-angular-animate.git#1.2.16
bower angular-animate#1.2.16  validate 1.2.16 against git://github.com/angular/bower-angular-animate.git#1.2.16
bower angular-sanitize#1.2.16   cached git://github.com/angular/bower-angular-sanitize.git#1.2.16
bower angular-sanitize#1.2.16 validate 1.2.16 against git://github.com/angular/bower-angular-sanitize.git#1.2.16
bower angular-touch#1.2.16      cached git://github.com/angular/bower-angular-touch.git#1.2.16
bower angular-touch#1.2.16    validate 1.2.16 against git://github.com/angular/bower-angular-touch.git#1.2.16
bower json3#~3.3.1              cached git://github.com/bestiejs/json3.git#3.3.2
bower json3#~3.3.1            validate 3.3.2 against git://github.com/bestiejs/json3.git#~3.3.1
bower angular-scenario#1.2.16   cached git://github.com/angular/bower-angular-scenario.git#1.2.16
bower angular-scenario#1.2.16 validate 1.2.16 against git://github.com/angular/bower-angular-scenario.git#1.2.16
bower angular-route#1.2.16      cached git://github.com/angular/bower-angular-route.git#1.2.16
bower angular-route#1.2.16    validate 1.2.16 against git://github.com/angular/bower-angular-route.git#1.2.16
bower es5-shim#~3.1.0           cached git://github.com/es-shims/es5-shim.git#3.1.1
bower es5-shim#~3.1.0         validate 3.1.1 against git://github.com/es-shims/es5-shim.git#~3.1.0
bower angular#1.2.16            cached git://github.com/angular/bower-angular.git#1.2.16
bower angular#1.2.16          validate 1.2.16 against git://github.com/angular/bower-angular.git#1.2.16
bower bootstrap#~3.1.1          cached git://github.com/twbs/bootstrap.git#3.1.1
bower bootstrap#~3.1.1        validate 3.1.1 against git://github.com/twbs/bootstrap.git#~3.1.1
bower angular-cookies#1.2.16    cached git://github.com/angular/bower-angular-cookies.git#1.2.16
bower angular-cookies#1.2.16  validate 1.2.16 against git://github.com/angular/bower-angular-cookies.git#1.2.16
 
> fsevents@0.3.1 install /Users/molinele/Desktop/bla/node_modules/karma/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

bower jquery#>= 1.9.0           cached git://github.com/jquery/jquery.git#2.1.3
bower jquery#>= 1.9.0         validate 2.1.3 against git://github.com/jquery/jquery.git#>= 1.9.0
bower angular-animate#1.2.16   install angular-animate#1.2.16
bower json3#~3.3.1             install json3#3.3.2
bower angular-sanitize#1.2.16  install angular-sanitize#1.2.16
bower angular-touch#1.2.16     install angular-touch#1.2.16
bower angular-resource#1.2.16  install angular-resource#1.2.16
bower angular-mocks#1.2.16     install angular-mocks#1.2.16
bower es5-shim#~3.1.0          install es5-shim#3.1.1
bower angular-scenario#1.2.16  install angular-scenario#1.2.16
bower angular-route#1.2.16     install angular-route#1.2.16
bower angular#1.2.16           install angular#1.2.16
bower bootstrap#~3.1.1         install bootstrap#3.1.1
bower angular-cookies#1.2.16   install angular-cookies#1.2.16
bower jquery#>= 1.9.0          install jquery#2.1.3
\
evalmachine.<anonymous>:865
  binding.chown(pathModule._makeLong(path), uid, gid, callback);
          ^
TypeError: gid must be an unsigned int
    at Object.fs.chown (evalmachine.<anonymous>:865:11)
    at Object.chown (/usr/local/lib/node_modules/bower/node_modules/graceful-fs/polyfills.js:141:17)
    at endChown (/usr/local/lib/node_modules/bower/node_modules/fstream/lib/writer.js:212:12)
    at setProps (/usr/local/lib/node_modules/bower/node_modules/fstream/lib/writer.js:298:5)
    at /usr/local/lib/node_modules/bower/node_modules/fstream/lib/writer.js:289:7
    at Object.oncomplete (evalmachine.<anonymous>:108:15)
app/index.html modified.
  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node: Finished
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  SOLINK_MODULE(target) Release/fse.node: Finished

> phantomjs@1.9.13 install /Users/molinele/Desktop/bla/node_modules/karma-phantomjs-launcher/node_modules/phantomjs
> node install.js

Download already available at /var/folders/3k/dt_h33fj5zbgd23ymcw9rbqrf9q9_0/T/phantomjs/phantomjs-1.9.8-macosx.zip
Extracting zip contents
Removing /Users/molinele/Desktop/bla/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom
Copying extracted folder /var/folders/3k/dt_h33fj5zbgd23ymcw9rbqrf9q9_0/T/phantomjs/phantomjs-1.9.8-macosx.zip-extract-1420340609878/phantomjs-1.9.8-macosx -> /Users/molinele/Desktop/bla/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom
Removing /var/folders/3k/dt_h33fj5zbgd23ymcw9rbqrf9q9_0/T/phantomjs/phantomjs-1.9.8-macosx.zip-extract-1420340609878
Writing location.js file
Done. Phantomjs binary available at /Users/molinele/Desktop/bla/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom/bin/phantomjs

> ws@0.4.32 install /Users/molinele/Desktop/bla/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished
npm WARN unmet dependency /Users/molinele/Desktop/bla/node_modules/grunt-google-cdn/node_modules/bower requires chalk@'0.5.0' but will load
npm WARN unmet dependency /Users/molinele/Desktop/bla/node_modules/grunt-google-cdn/node_modules/chalk,
npm WARN unmet dependency which is version 0.5.1
npm WARN unmet dependency /Users/molinele/Desktop/bla/node_modules/grunt-google-cdn/node_modules/google-cdn/node_modules/cdnjs-cdn-data requires semver@'~2.2.1' but will load
npm WARN unmet dependency /Users/molinele/Desktop/bla/node_modules/grunt-google-cdn/node_modules/google-cdn/node_modules/semver,
npm WARN unmet dependency which is version 2.3.2
npm WARN unmet dependency /Users/molinele/Desktop/bla/node_modules/grunt/node_modules/js-yaml/node_modules/argparse requires underscore.string@'~2.4.0' but will load
npm WARN unmet dependency /Users/molinele/Desktop/bla/node_modules/grunt/node_modules/underscore.string,
npm WARN unmet dependency which is version 2.2.1
npm WARN unmet dependency /Users/molinele/Desktop/bla/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress/node_modules/tar/node_modules/fstream requires mkdirp@'0.5' but will load
npm WARN unmet dependency /Users/molinele/Desktop/bla/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.3.5
npm WARN unmet dependency /Users/molinele/Desktop/bla/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-wrapper/node_modules/download/node_modules/decompress/node_modules/tar/node_modules/fstream requires mkdirp@'0.5' but will load
npm WARN unmet dependency /Users/molinele/Desktop/bla/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-wrapper/node_modules/download/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.3.5
npm WARN unmet dependency /Users/molinele/Desktop/bla/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-build/node_modules/download/node_modules/decompress/node_modules/tar/node_modules/fstream requires mkdirp@'0.5' but will load
npm WARN unmet dependency /Users/molinele/Desktop/bla/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-build/node_modules/download/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.3.5
npm WARN unmet dependency /Users/molinele/Desktop/bla/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-wrapper/node_modules/download/node_modules/decompress/node_modules/tar/node_modules/fstream requires mkdirp@'0.5' but will load
npm WARN unmet dependency /Users/molinele/Desktop/bla/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-wrapper/node_modules/download/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.3.5
npm WARN unmet dependency /Users/molinele/Desktop/bla/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-build/node_modules/download/node_modules/decompress/node_modules/tar/node_modules/fstream requires mkdirp@'0.5' but will load
npm WARN unmet dependency /Users/molinele/Desktop/bla/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-build/node_modules/download/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.3.5
npm WARN unmet dependency /Users/molinele/Desktop/bla/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-wrapper/node_modules/download/node_modules/decompress/node_modules/tar/node_modules/fstream requires mkdirp@'0.5' but will load
npm WARN unmet dependency /Users/molinele/Desktop/bla/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-wrapper/node_modules/download/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.3.5
npm WARN unmet dependency /Users/molinele/Desktop/bla/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin/node_modules/bin-build/node_modules/download/node_modules/decompress/node_modules/tar/node_modules/fstream requires mkdirp@'0.5' but will load
npm WARN unmet dependency /Users/molinele/Desktop/bla/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin/node_modules/bin-build/node_modules/download/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.3.5
npm WARN unmet dependency /Users/molinele/Desktop/bla/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin/node_modules/bin-wrapper/node_modules/download/node_modules/decompress/node_modules/tar/node_modules/fstream requires mkdirp@'0.5' but will load
npm WARN unmet dependency /Users/molinele/Desktop/bla/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin/node_modules/bin-wrapper/node_modules/download/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.3.5
grunt-karma@0.9.0 node_modules/grunt-karma
└── lodash@2.4.1

karma-phantomjs-launcher@0.1.4 node_modules/karma-phantomjs-launcher
└── phantomjs@1.9.13 (which@1.0.8, progress@1.1.8, rimraf@2.2.8, kew@0.4.0, ncp@1.0.1, request-progress@0.3.1, mkdirp@0.5.0, adm-zip@0.4.4, npmconf@2.0.9, request@2.42.0)

jasmine-core@2.1.3 node_modules/jasmine-core

karma@0.12.31 node_modules/karma
├── di@0.0.1
├── graceful-fs@2.0.3
├── rimraf@2.2.8
├── colors@0.6.2
├── mime@1.2.11
├── q@0.9.7
├── minimatch@0.2.14 (sigmund@1.0.0, lru-cache@2.5.0)
├── optimist@0.6.1 (wordwrap@0.0.2, minimist@0.0.10)
├── glob@3.2.11 (inherits@2.0.1, minimatch@0.3.0)
├── source-map@0.1.42 (amdefine@0.1.0)
├── log4js@0.6.21 (semver@1.1.4, async@0.2.10, readable-stream@1.0.33)
├── lodash@2.4.1
├── http-proxy@0.10.4 (pkginfo@0.3.0, utile@0.2.1)
├── connect@2.26.6 (cookie@0.1.2, fresh@0.2.4, pause@0.0.1, cookie-signature@1.0.5, response-time@2.0.1, vhost@3.0.0, basic-auth-connect@1.0.0, on-headers@1.0.0, bytes@1.0.0, media-typer@0.3.0, parseurl@1.3.0, cookie-parser@1.3.3, depd@0.4.5, connect-timeout@1.3.0, finalhandler@0.2.0, method-override@2.2.0, debug@2.0.0, qs@2.2.4, morgan@1.3.2, serve-favicon@2.1.7, type-is@1.5.5, express-session@1.8.2, csurf@1.6.4, multiparty@3.3.2, serve-static@1.6.4, errorhandler@1.2.4, compression@1.1.2, body-parser@1.8.4, serve-index@1.2.1)
├── useragent@2.0.10 (lru-cache@2.2.4)
├── chokidar@0.12.5 (async-each@0.1.6, readdirp@1.3.0, fsevents@0.3.1)
└── socket.io@0.9.16 (base64id@0.1.0, policyfile@0.0.4, redis@0.7.3, socket.io-client@0.9.16)

karma-jasmine@0.3.3 node_modules/karma-jasmine
-
> optipng-bin@0.3.11 postinstall /Users/molinele/Desktop/bla/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
> node index.js

⚠ pre-build test failed, compiling from source...
✔ optipng built successfully!

> jpegtran-bin@0.2.8 postinstall /Users/molinele/Desktop/bla/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin
> node index.js

✔ pre-build test passed successfully!
 
> pngquant-bin@0.3.5 postinstall /Users/molinele/Desktop/bla/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin
> node index.js

✔ pre-build test passed successfully!

> gifsicle@0.1.7 postinstall /Users/molinele/Desktop/bla/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
> node index.js

⚠ pre-build test failed, compiling from source...

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: invalid tar file
    at Extract.Parse._startEntry (/Users/molinele/Desktop/bla/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress/node_modules/tar/lib/parse.js:145:13)
    at Extract.Parse._process (/Users/molinele/Desktop/bla/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress/node_modules/tar/lib/parse.js:127:12)
    at BlockStream.<anonymous> (/Users/molinele/Desktop/bla/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress/node_modules/tar/lib/parse.js:47:8)
    at BlockStream.emit (events.js:95:17)
    at BlockStream._emitChunk (/Users/molinele/Desktop/bla/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress/node_modules/tar/node_modules/block-stream/block-stream.js:145:10)
    at BlockStream.resume (/Users/molinele/Desktop/bla/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress/node_modules/tar/node_modules/block-stream/block-stream.js:58:15)
    at Extract.Reader.resume (/Users/molinele/Desktop/bla/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress/node_modules/tar/node_modules/fstream/lib/reader.js:255:34)
    at DirWriter.<anonymous> (/Users/molinele/Desktop/bla/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress/node_modules/tar/lib/extract.js:57:8)
    at DirWriter.emit (events.js:92:17)
    at /Users/molinele/Desktop/bla/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress/node_modules/tar/node_modules/fstream/lib/dir-writer.js:39:8
npm WARN optional dep failed, continuing imagemin-gifsicle@0.1.1
grunt-contrib-copy@0.5.0 node_modules/grunt-contrib-copy

grunt-contrib-concat@0.4.0 node_modules/grunt-contrib-concat
└── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)

grunt-filerev@0.2.1 node_modules/grunt-filerev
├── each-async@0.1.3
└── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)

jshint-stylish@0.2.0 node_modules/jshint-stylish
├── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)
└── text-table@0.2.0

grunt-concurrent@0.5.0 node_modules/grunt-concurrent
├── pad-stdio@0.1.1 (lpad@0.2.1)
└── async@0.2.10

grunt-contrib-clean@0.5.0 node_modules/grunt-contrib-clean
└── rimraf@2.2.8

time-grunt@0.3.2 node_modules/time-grunt
├── date-time@0.1.1
├── pretty-ms@0.1.0
├── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)
├── text-table@0.2.0
└── hooker@0.2.3

grunt-newer@0.7.0 node_modules/grunt-newer
├── rimraf@2.2.6
└── async@0.2.10

grunt-contrib-cssmin@0.9.0 node_modules/grunt-contrib-cssmin
├── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)
├── clean-css@2.1.8 (commander@2.1.0)
└── maxmin@0.1.0 (pretty-bytes@0.1.2, gzip-size@0.1.1)

grunt-contrib-uglify@0.4.1 node_modules/grunt-contrib-uglify
├── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)
├── maxmin@0.1.0 (pretty-bytes@0.1.2, gzip-size@0.1.1)
└── uglify-js@2.4.16 (uglify-to-browserify@1.0.2, async@0.2.10, optimist@0.3.7, source-map@0.1.34)

grunt-ngmin@0.0.3 node_modules/grunt-ngmin
└── ngmin@0.4.1 (astral@0.1.0, clone@0.1.19, commander@1.1.1, astral-angular-annotate@0.0.2, escodegen@0.0.28, esprima@1.0.4)

grunt-contrib-watch@0.6.1 node_modules/grunt-contrib-watch
├── async@0.2.10
├── tiny-lr-fork@0.0.5 (debug@0.7.4, faye-websocket@0.4.4, noptify@0.0.3, qs@0.5.6)
├── gaze@0.5.1 (globule@0.1.0)
└── lodash@2.4.1

grunt-usemin@2.6.2 node_modules/grunt-usemin
├── debug@2.1.1 (ms@0.6.2)
├── chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
└── lodash@2.4.1

load-grunt-tasks@0.4.0 node_modules/load-grunt-tasks
├── multimatch@0.1.0 (minimatch@0.2.14, lodash@2.4.1)
└── findup-sync@0.1.3 (glob@3.2.11, lodash@2.4.1)

grunt-contrib-htmlmin@0.3.0 node_modules/grunt-contrib-htmlmin
├── pretty-bytes@0.1.2
├── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)
└── html-minifier@0.6.9 (relateurl@0.2.6, change-case@2.1.6, clean-css@2.2.22, cli@0.6.5, uglify-js@2.4.16)

grunt@0.4.5 node_modules/grunt
├── which@1.0.8
├── dateformat@1.0.2-1.2.3
├── eventemitter2@0.4.14
├── getobject@0.1.0
├── rimraf@2.2.8
├── colors@0.6.2
├── async@0.1.22
├── hooker@0.2.3
├── grunt-legacy-util@0.2.0
├── nopt@1.0.10 (abbrev@1.0.5)
├── exit@0.1.2
├── minimatch@0.2.14 (sigmund@1.0.0, lru-cache@2.5.0)
├── glob@3.1.21 (inherits@1.0.0, graceful-fs@1.2.3)
├── lodash@0.9.2
├── coffee-script@1.3.3
├── underscore.string@2.2.1
├── iconv-lite@0.2.11
├── findup-sync@0.1.3 (glob@3.2.11, lodash@2.4.1)
├── grunt-legacy-log@0.1.1 (underscore.string@2.3.3, lodash@2.4.1)
└── js-yaml@2.0.5 (argparse@0.1.16, esprima@1.0.4)

grunt-svgmin@0.4.0 node_modules/grunt-svgmin
├── each-async@0.1.3
├── pretty-bytes@0.1.2
├── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)
└── svgo@0.4.5 (colors@0.6.2, whet.extend@0.9.9, coa@0.4.1, sax@0.6.1, js-yaml@2.1.3)

grunt-wiredep@1.9.0 node_modules/grunt-wiredep
└── wiredep@1.8.6 (propprop@0.3.0, minimist@1.1.0, chalk@0.5.1, through2@0.6.3, glob@4.3.2, lodash@2.4.1, bower-config@0.5.2)

grunt-contrib-jshint@0.10.0 node_modules/grunt-contrib-jshint
├── hooker@0.2.3
└── jshint@2.5.11 (strip-json-comments@1.0.2, underscore@1.6.0, exit@0.1.2, console-browserify@1.1.0, minimatch@1.0.0, shelljs@0.3.0, cli@0.6.5, htmlparser2@3.8.2)

grunt-contrib-imagemin@0.7.2 node_modules/grunt-contrib-imagemin
├── pretty-bytes@0.1.2
├── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)
├── async@0.7.0
└── imagemin@0.4.9 (stat-mode@0.2.0, ware@0.3.0, rimraf@2.2.8, image-type@0.1.4, nopt@3.0.1, tempfile@0.1.3, fs-extra@0.10.0, imagemin-svgo@0.1.1, imagemin-optipng@0.1.0, imagemin-jpegtran@0.1.0, imagemin-pngquant@0.1.3)

grunt-contrib-connect@0.7.1 node_modules/grunt-contrib-connect
├── connect-livereload@0.3.2
├── open@0.0.4
├── async@0.2.10
├── portscanner@0.2.2 (async@0.1.15)
└── connect@2.13.1 (uid2@0.0.3, methods@0.1.0, pause@0.0.1, debug@0.8.1, cookie-signature@1.0.1, fresh@0.2.0, qs@0.6.6, bytes@0.2.1, buffer-crc32@0.2.1, raw-body@1.1.3, batch@0.5.0, cookie@0.1.0, compressible@1.0.0, negotiator@0.3.0, send@0.1.4, multiparty@2.2.0)

grunt-autoprefixer@0.7.6 node_modules/grunt-autoprefixer
├── diff@1.0.8
├── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)
└── autoprefixer@1.3.1 (fs-extra@0.9.1, postcss@0.3.5, caniuse-db@1.0.30000042)

grunt-google-cdn@0.4.3 node_modules/grunt-google-cdn
├── chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
├── google-cdn@0.7.0 (regexp-quote@0.0.0, google-cdn-data@0.1.15, async@0.9.0, debug@1.0.4, semver@2.3.2, cdnjs-cdn-data@0.1.1)
└── bower@1.3.12 (is-root@1.0.0, junk@1.0.0, stringify-object@1.0.0, which@1.0.8, abbrev@1.0.5, chmodr@0.1.0, osenv@0.1.0, archy@0.0.2, opn@1.0.1, rimraf@2.2.8, lru-cache@2.5.0, bower-logger@0.2.2, bower-endpoint-parser@0.2.2, graceful-fs@3.0.5, lockfile@1.0.0, nopt@3.0.1, retry@0.6.0, tmp@0.0.23, request-progress@0.3.0, q@1.0.1, chalk@0.5.0, shell-quote@1.4.2, bower-json@0.4.0, semver@2.3.2, fstream@1.0.3, mkdirp@0.5.0, p-throttler@0.1.0, promptly@0.2.0, bower-config@0.5.2, fstream-ignore@1.0.2, tar-fs@0.5.2, decompress-zip@0.0.8, request@2.42.0, glob@4.0.6, bower-registry-client@0.2.1, cardinal@0.4.0, update-notifier@0.2.0, mout@0.9.1, handlebars@2.0.0, inquirer@0.7.1, insight@0.4.3)
```

I've checked and there doesn't seem to be an issue with permissions (all the node_modules have staff permissions), so I'm not sure why guid would be negative.

Thanks in advance.

**Comment by jasnell** [comment]
Does not appear to be a node issue.

**Comment by cjihrig** [comment]
Thanks @jasnell. If this does turn out to be a Node issue, just let me know.

**Comment by ejmolinelli** [comment]
will do, thanks for the help. It does appear to be an npm issue.
