### ISSUE TITLE
Build fails on RedHat6

### ISSUE THREAD

**Issue by JacksonTian** [joyent/node#9024]
```
../src/cares_wrap.cc: In constructor 'node::cares_wrap::GetAddrInfoReqWrap::GetAddrInfoReqWrap(node::Environment*, v8::Local<v8::Object>)':
../src/cares_wrap.cc:77: error: class 'node::cares_wrap::GetAddrInfoReqWrap' does not have any field named 'ReqWrap'
../src/cares_wrap.cc:77: error: no matching function for call to 'node::ReqWrap<uv_getaddrinfo_s>::ReqWrap()'
../src/req_wrap.h:37: note: candidates are: node::ReqWrap<T>::ReqWrap(node::Environment*, v8::Handle<v8::Object>, node::AsyncWrap::ProviderType) [with T = uv_getaddrinfo_s]
../src/req_wrap.h:35: note:                 node::ReqWrap<uv_getaddrinfo_s>::ReqWrap(const node::ReqWrap<uv_getaddrinfo_s>&)
../src/cares_wrap.cc: In constructor 'node::cares_wrap::GetNameInfoReqWrap::GetNameInfoReqWrap(node::Environment*, v8::Local<v8::Object>)':
../src/cares_wrap.cc:94: error: class 'node::cares_wrap::GetNameInfoReqWrap' does not have any field named 'ReqWrap'
../src/cares_wrap.cc:94: error: no matching function for call to 'node::ReqWrap<uv_getnameinfo_s>::ReqWrap()'
../src/req_wrap.h:37: note: candidates are: node::ReqWrap<T>::ReqWrap(node::Environment*, v8::Handle<v8::Object>, node::AsyncWrap::ProviderType) [with T = uv_getnameinfo_s]
../src/req_wrap.h:35: note:                 node::ReqWrap<uv_getnameinfo_s>::ReqWrap(const node::ReqWrap<uv_getnameinfo_s>&)
../src/node_v8.cc: In member function 'void node::Environment::IsolateData::AfterGarbageCollection(v8::GCType, v8::GCCallbackFlags)':
../src/node_v8.cc:78: warning: dereferencing type-punned pointer will break strict-aliasing rules
../src/node_v8.cc:80: warning: dereferencing type-punned pointer will break strict-aliasing rules
../src/node_v8.cc:81: warning: dereferencing type-punned pointer will break strict-aliasing rules
../src/node_v8.cc:81: warning: dereferencing type-punned pointer will break strict-aliasing rules
../src/node_v8.cc:81: warning: dereferencing type-punned pointer will break strict-aliasing rules
../src/node_v8.cc:81: warning: dereferencing type-punned pointer will break strict-aliasing rules
```
CC: 
```
+ cc -v
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.6 20110731 (Red Hat 4.4.6-3) (GCC) 
+ g++ -v
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.6 20110731 (Red Hat 4.4.6-3) (GCC) 
```

**Comment by misterdjules** [comment]
@JacksonTian What branch did you try to build?

**Comment by JacksonTian** [comment]
v0.12

**Comment by BowlingX** [comment]
same here with Debian (6.0.10, squeeze) gcc version 4.4.5 (Debian 4.4.5-8)

**Comment by rochal** [comment]
same here for v0.11.15 on CentOs 6.5

```
../src/cares_wrap.cc:76: error: class ‘node::cares_wrap::GetAddrInfoReqWrap’ does not have any field named ‘ReqWrap’
../src/cares_wrap.cc:76: error: no matching function for call to ‘node::ReqWrap<uv_getaddrinfo_s>::ReqWrap()’
../src/req_wrap.h:37: note: candidates are: node::ReqWrap<T>::ReqWrap(node::Environment*, v8::Handle<v8::Object>, node::
AsyncWrap::ProviderType) [with T = uv_getaddrinfo_s]
../src/req_wrap.h:35: note:                 node::ReqWrap<uv_getaddrinfo_s>::ReqWrap(const node::ReqWrap<uv_getaddrinfo_
s>&)
../src/cares_wrap.cc: In constructor ‘node::cares_wrap::GetNameInfoReqWrap::GetNameInfoReqWrap(node::Environment*, v8::L
ocal<v8::Object>)’:
../src/cares_wrap.cc:93: error: class ‘node::cares_wrap::GetNameInfoReqWrap’ does not have any field named ‘ReqWrap’
../src/cares_wrap.cc:93: error: no matching function for call to ‘node::ReqWrap<uv_getnameinfo_s>::ReqWrap()’
../src/req_wrap.h:37: note: candidates are: node::ReqWrap<T>::ReqWrap(node::Environment*, v8::Handle<v8::Object>, node::
AsyncWrap::ProviderType) [with T = uv_getnameinfo_s]
../src/req_wrap.h:35: note:                 node::ReqWrap<uv_getnameinfo_s>::ReqWrap(const node::ReqWrap<uv_getnameinfo_
s>&)
In file included from ../src/cares_wrap.cc:29:
```

**Comment by misterdjules** [comment]
This should be fixed by https://github.com/joyent/node/pull/9098.

**Comment by misterdjules** [comment]
Fixed by https://github.com/joyent/node/commit/59265264d56cfb7ced87f9b3666ec570152c5f47, please let us know if that works for you. Thank you!

**Comment by JacksonTian** [comment]
Thanks @misterdjules , I will try it later.

**Comment by rochal** [comment]
```
napshot.a -Wl,--end-group -lrt -lm -ldl
  LINK(target) /home/vagrant/node/out/Release/node: Finished
  touch /home/vagrant/node/out/Release/obj.target/node_dtrace_header.stamp
  touch /home/vagrant/node/out/Release/obj.target/node_dtrace_provider.stamp
  touch /home/vagrant/node/out/Release/obj.target/node_dtrace_ustack.stamp
  touch /home/vagrant/node/out/Release/obj.target/node_etw.stamp
  touch /home/vagrant/node/out/Release/obj.target/node_mdb.stamp
  touch /home/vagrant/node/out/Release/obj.target/node_perfctr.stamp
  touch /home/vagrant/node/out/Release/obj.target/specialize_node_d.stamp
make[1]: Leaving directory `/home/vagrant/node/out'
ln -fs out/Release/node node
[vagrant@vagrant node]$ cat /etc/redhat-release
CentOS release 6.5 (Final)
```

Looks good now, thanks!

**Comment by misterdjules** [comment]
@rochal Thank you very much for letting us know! Bonus question, does it run properly? :)

**Comment by rochal** [comment]
Looks good after make install.

When I run make test I get following output:

```
[vagrant@vagrant node]$ node -v
v0.11.16-pre
[vagrant@vagrant node]$ make test
make -C out BUILDTYPE=Release V=1
make[1]: Entering directory `/home/vagrant/node/out'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/vagrant/node/out'
ln -fs out/Release/node node
/usr/bin/python tools/test.py --mode=release simple message
=== release test-dgram-broadcast-multi-process ===
Path: simple/test-dgram-broadcast-multi-process
/home/vagrant/node/test/simple/test-dgram-broadcast-multi-process.js:187
          if (err) throw err;
                         ^
Error: send EPERM
    at exports._errnoException (util.js:746:11)
    at SendWrap.afterSend [as oncomplete] (dgram.js:348:23)
Command: out/Release/node /home/vagrant/node/test/simple/test-dgram-broadcast-multi-process.js
=== release test-dgram-empty-packet ===
Path: simple/test-dgram-empty-packet
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: bind EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at dgram.js:224:28
    at dns.js:85:18
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
Command: out/Release/node /home/vagrant/node/test/simple/test-dgram-empty-packet.js
=== release test-dgram-implicit-bind ===
Path: simple/test-dgram-implicit-bind
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: bind EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at dgram.js:224:28
    at dns.js:85:18
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
Command: out/Release/node /home/vagrant/node/test/simple/test-dgram-implicit-bind.js
=== release test-dgram-multicast-setTTL ===
Path: simple/test-dgram-multicast-setTTL
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: bind EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at dgram.js:224:28
    at dns.js:85:18
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
Command: out/Release/node /home/vagrant/node/test/simple/test-dgram-multicast-setTTL.js
=== release test-dgram-pingpong ===
Path: simple/test-dgram-pingpong
server listening on 12348 undefined
Client sending to 12348, localhost PING
/home/vagrant/node/test/simple/test-dgram-pingpong.js:55
    throw e;
          ^
Error: bind EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at dgram.js:224:28
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:81:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)
Command: out/Release/node /home/vagrant/node/test/simple/test-dgram-pingpong.js
=== release test-dgram-send-empty-buffer ===
Path: simple/test-dgram-send-empty-buffer
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: bind EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at dgram.js:224:28
    at dns.js:85:18
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
Command: out/Release/node /home/vagrant/node/test/simple/test-dgram-send-empty-buffer.js
=== release test-vm-timeout ===
Path: simple/test-vm-timeout
Command: out/Release/node /home/vagrant/node/test/simple/test-vm-timeout.js
--- TIMEOUT ---
[04:01|% 100|+ 774|-   7]: Done
make: *** [test] Error 1
```

**Comment by misterdjules** [comment]
@rochal Thanks! The failing tests don't look too concerning to me. Is there a chance that there's already another program binding port 12346 on your system at the time these tests run?
