### ISSUE TITLE
"Error: Module did not self-register." when installing a package on 0.11.14

### ISSUE THREAD

**Issue by varya** [joyent/node#9040]
I have issues with installing a packge on `0.11.14`, which worked correctly with `0.10.x`.

Running `npm install sc5-styleguide` gives me this error:

```
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/varya/WebDev/SC5/tmp/node_modules/sc5-styleguide/node_modules/kss/node_modules/node-sass/lib/index.js:181:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

Googling for a problem I found things like this issue https://github.com/joyent/node/issues/7116 which is closed as fixed. But in my case error still exists. Also is reproduced with `0.11.13`. I use `nvm` if matters

**Comment by misterdjules** [comment]
It seems that's it's an issue with node-sass. See https://github.com/sass/node-sass/issues/550 and https://github.com/sass/node-sass/issues/517. You might want to make sc5-styleguide depend on node-sass@2.0.0-beta or later.

Closing, but please feel free to let us know if you still think it's an issue with node's core.

Thank you!
