### ISSUE TITLE
Error in vcbuild.bat nosign debug

### ISSUE THREAD

**Issue by KrishPS** [joyent/node#9111]
Hi,

I am new to JS. I downloaded node code from your directory. When I tried to run the command "vcbuild.bat nosign debug" It gave me below error.Could you please help to identify the problem?

Error:
1. ctrpp not found in WinSDK path--using pre-gen files from tools/msvs/genfiles.

2. creating  config.mk
Traceback (most recent call last):
  File "tools/gyp_node.py", line 57, in <module>
    run_gyp(gyp_args)
  File "tools/gyp_node.py", line 18, in run_gyp
    rc = gyp.main(args)
  File ".\tools\gyp\pylib\gyp\__init__.py", line 527, in main
    return gyp_main(args)
  File ".\tools\gyp\pylib\gyp\__init__.py", line 503, in gyp_main
    options.circular_check)
  File ".\tools\gyp\pylib\gyp\__init__.py", line 129, in Load
    params['parallel'], params['root_targets'])
  File ".\tools\gyp\pylib\gyp\input.py", line 2692, in Load
    variables, includes, depth, check, True)
  File ".\tools\gyp\pylib\gyp\input.py", line 438, in LoadTargetBuildFile
    includes, depth, check, load_dependencies)
  File ".\tools\gyp\pylib\gyp\input.py", line 388, in LoadTargetBuildFile
    build_file_data, PHASE_EARLY, variables, build_file_path)
  File ".\tools\gyp\pylib\gyp\input.py", line 1237, in ProcessVariablesAndCondit
ionsInDict
    build_file)
  File ".\tools\gyp\pylib\gyp\input.py", line 1252, in ProcessVariablesAndCondit
ionsInList
    ProcessVariablesAndConditionsInDict(item, phase, variables, build_file)
  File ".\tools\gyp\pylib\gyp\input.py", line 1211, in ProcessVariablesAndCondit
ionsInDict
    ProcessConditionsInDict(the_dict, phase, variables, build_file)
  File ".\tools\gyp\pylib\gyp\input.py", line 1088, in ProcessConditionsInDict
    variables, build_file)
  File ".\tools\gyp\pylib\gyp\input.py", line 1159, in ProcessVariablesAndCondit
ionsInDict
    variables, build_file, 'variables')
  File ".\tools\gyp\pylib\gyp\input.py", line 1166, in ProcessVariablesAndCondit
ionsInDict
    expanded = ExpandVariables(value, phase, variables, build_file)
  File ".\tools\gyp\pylib\gyp\input.py", line 890, in ExpandVariables
    cwd=build_file_dir)
  File "C:\workspace\depot_tools\python276_bin\lib\subprocess.py", line 709, in
__init__
    errread, errwrite)
  File "C:\workspace\depot_tools\python276_bin\lib\subprocess.py", line 957, in
_execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

Thanks in Advance

**Comment by misterdjules** [comment]
Could you please try to build node with `vcbuild.bat nosign debug noperfctr` and let us know how it goes either in [the Node.js Google group](https://groups.google.com/forum/#!forum/nodejs) or [on StackOverflow](http://stackoverflow.com/questions/tagged/node.js)?

Closing here as this issue tracker is used to track actual bugs in Node.js' core, not general issues that are not bugs in Node.js' core itself, but I'll be happy to help in the Google group or at StackOverflow.

Thank you!

**Comment by textbook** [comment]
Related: http://stackoverflow.com/q/28235125/3001761
