### ISSUE TITLE
Error: Failed parsing JSON config key prefix: "C:\Program Files\nodejs"

### ISSUE THREAD

**Issue by tekoscott** [joyent/node#9169]
I am trying to run nodejs on a Micrsoft Surface 3 i7 512Gb with Windows 8.1 Pro as an operating system

Node.exe works fine. I can create the 'Hello World' program and it works brilliantly.

The issue I have is when I try to run the following commands with npm.
- npm cache clean
- npm init
When i attempt to run these commands on the command prompt i get the following error message:

C:\testdir>npm init
Error: Failed parsing JSON config key prefix: "C:\Program Files\nodejs"
    at parseField (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:376:13)
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:328:17
    at Array.forEach (native)
    at Conf.add (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:327:23)
    at ConfigChain.addString (C:\Program Files\nodejs\node_modules\npm\node_modules\config-chain\index.js:244:8)
    at Conf.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:315:10)
    at fs.js:336:14
    at FSReqWrap.oncomplete (fs.js:99:15)

Please note that I have given the directory as listed above full permissions, and unchecked the readonly checkbox on the folders properties dialog.

Can someone tell me if this is a recognised bug or am I missing something.

Kind Regards

Scott Brady

**Comment by tekoscott** [comment]
Forgot to say. I am using the latest version of node v 0.12.0

**Comment by KenanY** [comment]
This looks like an `npm` issue. Could you open this issue over at the [`npm` issue tracker](https://github.com/npm/npm)?

**Comment by tekoscott** [comment]
Closing issue here and reopening in npm repository
