### ISSUE TITLE
Mac Compile Error: 0.12.0

### ISSUE THREAD

**Issue by jmervine** [joyent/node#9182]
Apologies if this has already been reported, I searched and found nothing. I'm getting the following error when compiling 0.12.0 on my Mac. 

### Error
```
  cc '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_DARWIN_UNLIMITED_SELECT=1' -I../deps/uv/include -I../deps/uv/src  -Os -gdwarf-2 -mmacosx-version-min=10.5 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -Wall -Wextra -Wno-unused-parameter -g --std=gnu89 -pedantic -fno-strict-aliasing -MMD -MF /private/tmp/node/out/Release/.deps//private/tmp/node/out/Release/obj.target/libuv/deps/uv/src/threadpool.o.d.raw  -c -o /private/tmp/node/out/Release/obj.target/libuv/deps/uv/src/threadpool.o ../deps/uv/src/threadpool.c
In file included from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:55,
                 from ../deps/uv/src/unix/internal.h:52,
                 from ../deps/uv/src/threadpool.c:25:
/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:262: error: expected ‘,’ or ‘}’ before ‘__attribute__’
/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:414: error: expected ‘,’ or ‘}’ before ‘__attribute__’
make[1]: *** [/private/tmp/node/out/Release/obj.target/libuv/deps/uv/src/threadpool.o] Error 1
make: *** [node] Error 2
```

### Build Seteps

```
git clone git://github.com/joyent/node.git

cd node
git checkout v$VERSION

export JOBS=4

./configure --prefix=/usr
make
```

### Sys Info

* OS Version: 10.10.2 (14C109)
* XCode Version: 6.1.1 (6A2008a)

```
$ uname -a
Darwin CA02MLJM974A 14.1.0 Darwin Kernel Version 14.1.0: Mon Dec 22 23:10:38 PST 2014; root:xnu-2782.10.72~2/RELEASE_X86_64 x86_64
```

Please let me know if you need any additional information.

**Comment by SheetJSDev** [comment]
@jmervine went through this process a few hours ago without a hitch.  The only difference was that I ran `./configure` without the option `--prefix=/usr`

What gcc version are you running? Share the output of `gcc --version`.

```
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.0.0
Thread model: posix
```

**Comment by giano** [comment]
Same with many modules (memwatch, strong-memwatch, toobusy, etc..)

**Comment by lern** [comment]
I'm seeing the same issue when trying to install node using homebrew with `--without-npm`.

```
~$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.1.0
Thread model: posix

~$ brew install node --without-npm
==> Downloading https://nodejs.org/dist/v0.12.0/node-v0.12.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/node-0.12.0.tar.gz
==> ./configure --prefix=/usr/local/Cellar/node/0.12.0 --without-npm --without-ssl2 --without-ssl3
==> make install
/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:414:38: error: expected ',' or '}' before '__attribute__'
   kFSEventStreamEventFlagItemCreated __OSX_AVAILABLE_STARTING(__MAC_10_7, __IPHONE_6_0) = 0x00000100,
                                      ^
make[1]: *** [/private/tmp/node-PVTS3E/node-v0.12.0/out/Release/obj.target/libuv/deps/uv/src/unix/getnameinfo.o] Error 1
make: *** [node] Error 2

READ THIS: http://git.io/brew-troubleshooting

These open issues may also help:
node and icu4c Yosemite bottles have different C++ standard libraries (https://github.com/Homebrew/homebrew/issues/36681)
Adding formulas for ndenv and node-build. Inspired by rbenv and ruby-build formulas. (https://github.com/Homebrew/homebrew/pull/34994)
```

**Comment by SheetJSDev** [comment]
@lern does building from source work for you?

```
$ git clone https://github.com/joyent/node
$ cd node
$ git checkout v0.12.0-release
$ ./configure
$ make -j
```

**Comment by jmervine** [comment]
I updated my install commands to include "v0.12.0-release" (instead of v0.12.0) and use `make -j` (instead of `make`). I got the following error:

```
  cc '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_DARWIN_UNLIMITED_SELECT=1' -I../deps/uv/include -I../deps/uv/src  -Os -gdwarf-2 -mmacosx-version-min=10.5 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -Wall -Wextra -Wno-unused-parameter -g --std=gnu89 -pedantic -fno-strict-aliasing -MMD -MF /private/tmp/node/out/Release/.deps//private/tmp/node/out/Release/obj.target/libuv/deps/uv/src/unix/loop-watcher.o.d.raw  -c -o /private/tmp/node/out/Release/obj.target/libuv/deps/uv/src/unix/loop-watcher.o ../deps/uv/src/unix/loop-watcher.c
In file included from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:55,
                 from ../deps/uv/src/unix/internal.h:52,
                 from ../deps/uv/src/unix/core.c:22:
/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:262: error: expected ‘,’ or ‘}’ before ‘__attribute__’
/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:414: error: expected ‘,’ or ‘}’ before ‘__attribute__’
make[1]: *** [/private/tmp/node/out/Release/obj.target/libuv/deps/uv/src/unix/core.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [/private/tmp/node/out/Release/obj.target/libuv/deps/uv/src/unix/async.o] Error 1
make[1]: *** [/private/tmp/node/out/Release/obj.target/libuv/deps/uv/src/threadpool.o] Error 1
In file included from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:55,
                 from ../deps/uv/src/unix/internal.h:52,
                 from ../deps/uv/src/unix/dl.c:23:
/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:262: error: expected ‘,’ or ‘}’ before ‘__attribute__’
/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:414: error: expected ‘,’ or ‘}’ before ‘__attribute__’
make[1]: *** [/private/tmp/node/out/Release/obj.target/libuv/deps/uv/src/unix/dl.o] Error 1
In file included from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:55,
                 from ../deps/uv/src/unix/internal.h:52,
                 from ../deps/uv/src/unix/fs.c:30:
/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:262: error: expected ‘,’ or ‘}’ before ‘__attribute__’
/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:414: error: expected ‘,’ or ‘}’ before ‘__attribute__’
make[1]: *** [/private/tmp/node/out/Release/obj.target/libuv/deps/uv/src/unix/fs.o] Error 1
In file included from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:55,
                 from ../deps/uv/src/unix/internal.h:52,
                 from ../deps/uv/src/unix/getnameinfo.c:28:
/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:262: error: expected ‘,’ or ‘}’ before ‘__attribute__’
/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:414: error: expected ‘,’ or ‘}’ before ‘__attribute__’
make[1]: *** [/private/tmp/node/out/Release/obj.target/libuv/deps/uv/src/unix/getnameinfo.o] Error 1
In file included from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:55,
                 from ../deps/uv/src/unix/internal.h:52,
                 from ../deps/uv/src/unix/getaddrinfo.c:29:
/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:262: error: expected ‘,’ or ‘}’ before ‘__attribute__’
/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:414: error: expected ‘,’ or ‘}’ before ‘__attribute__’
make[1]: *** [/private/tmp/node/out/Release/obj.target/libuv/deps/uv/src/unix/getaddrinfo.o] Error 1
In file included from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:55,
                 from ../deps/uv/src/unix/internal.h:52,
                 from ../deps/uv/src/unix/loop.c:24:
/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:262: error: expected ‘,’ or ‘}’ before ‘__attribute__’
/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:414: error: expected ‘,’ or ‘}’ before ‘__attribute__’
In file included from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:55,
                 from ../deps/uv/src/unix/internal.h:52,
                 from ../deps/uv/src/unix/loop-watcher.c:23:
/System/Library/Fr`ameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:262: error: expected ‘,’ or ‘}’ before ‘__attribute__’
/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:414: error: expected ‘,’ or ‘}’ before ‘__attribute__’
make[1]: *** [/private/tmp/node/out/Release/obj.target/libuv/deps/uv/src/unix/loop.o] Error 1
make[1]: *** [/private/tmp/node/out/Release/obj.target/libuv/deps/uv/src/unix/loop-watcher.o] Error 1
make: *** [node] Error 2
```

Additionally, my `g++` version is the same as @lern above:

```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.1.0
Thread model: posix
```

**Comment by lern** [comment]
@SheetJSDev building from source worked fine for me. Note that I used `./configure --without-npm`.

**Comment by misterdjules** [comment]
Is `cc` pointing to `gcc` on your system? It seems that on Yosemite, [some framework headers use a specific clang extension not supported by GCC](https://stackoverflow.com/questions/22519756/macports-gcc-4-8-2-error-with-mmacosx-version-min-and-foundation-headers).

If you're using gcc/g++ on OS X, could you please try to build node with clang instead and let us know how it goes?

Thank you!

**Comment by misterdjules** [comment]
@jmervine Closing for lack of activity, and because we haben't found a way to reproduce the original issue. But please let us know if we should reopen it. Thank you!

**Comment by bjm88** [comment]
I get this error after upgrading to node 0.12.4 on mac os X 10.10
build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Ben/caredox/caredox_util/node_modules/fsevents
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok 
npm WARN install:fsevents fsevents@0.3.8 install: `node-gyp rebuild`
npm WARN install:fsevents Exit status 1

uname -a
Darwin new-host-2.home 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64
Benjamins-MBP:caredox_util Ben$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
