### ISSUE TITLE
"Module did not self register" error when requiring a module in v0.12.0

### ISSUE THREAD

**Issue by AlexanderGalen** [joyent/node#9252]
This is the error I get when executing a script that requires a few modules:
```
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Volumes/RESOURCE/node_modules/hummus/hummus.js:2:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```
 Apparently it's having trouble loading the 'hummus' module I'm using, but I'm fairly confident that it's not a bug with that module as I experience the same thing with a few other modules, and I don't have this problem in v0.10.36. 

I spent a few hours trying to figure this out without much luck. Honestly a lot of this is over my head. I re-installed node multiple times throughout the process, and the only solution that worked for me was just using v0.10.36, which is obviously not ideal.

**Comment by meandmycode** [comment]
Hummus is a native module and I would take a guess that it's just not compatible with either node or v8 in 0.12, you should do an outreach to the author of it https://github.com/galkahana/HummusJS/

**Comment by trevnorris** [comment]
Sorry. Nothing we can do on this end.
