### ISSUE TITLE
Cannot find module 'wrappy'

### ISSUE THREAD

**Issue by fastest963** [joyent/node#9299]
After compiling node.js v0.12.0 `npm -v` returns
```
module.js:340
    throw err;
          ^
Error: Cannot find module 'wrappy'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:367:17)
    at require (module.js:386:17)
    at Object.<anonymous> (/usr/lib/node_modules/once/once.js:1:76)
    at Module._compile (module.js:462:26)
    at Object.Module._extensions..js (module.js:480:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:367:17)
```
This seems to stem from there being a symlink from `/usr/lib/node_modules/npm/node_modules/once` to `/usr/lib/node_modules/once` but not a symlink for `/usr/lib/node_modules/npm/node_modules/wrappy` which is required by once.

With NODE_DEBUG=module (and a few more debug's added myself):
```
MODULE 16536: looking for "once" in ["/usr/lib/node_modules/npm/lib/config/node_modules","/usr/lib/node_modules/npm/lib/node_modules","/usr/lib/node_modules/npm/node_modules","/usr/lib/node_modules","/usr/node_modules","/node_modules","/root/.node_modules","/root/.node_libraries","/usr/lib/node"]
MODULE 16536: request once
MODULE 16536: trying /usr/lib/node_modules/npm/lib/config/node_modules/once
MODULE 16536: trying /usr/lib/node_modules/npm/lib/node_modules/once
MODULE 16536: trying /usr/lib/node_modules/npm/node_modules/once
MODULE 16536: load "/usr/lib/node_modules/once/once.js" for module "/usr/lib/node_modules/once/once.js"
MODULE 16536: Module._load REQUEST  wrappy parent: /usr/lib/node_modules/once/once.js
MODULE 16572: looking for "wrappy" in ["/usr/lib/node_modules/once/node_modules","/usr/lib/node_modules","/usr/node_modules","/node_modules","/root/.nodbraries","/usr/lib/node"]
MODULE 16572: request wrappy
MODULE 16572: trying /usr/lib/node_modules/once/node_modules/wrappy
MODULE 16572: trying /usr/lib/node_modules/wrappy
MODULE 16572: trying /usr/node_modules/wrappy
MODULE 16572: trying /node_modules/wrappy
MODULE 16572: trying /root/.node_modules/wrappy
MODULE 16572: trying /root/.node_libraries/wrappy
MODULE 16572: trying /usr/lib/node/wrappy
```

**Comment by fastest963** [comment]
So this just ended up being an issue with installing a v0.12.0 rpm over a v0.10.x install. The v0.12.0 rpm should delete the `/usr/lib/node_modules/npm` folder first. I did this via a pre script:

```
%pre
/bin/rm -rf %{_prefix}/lib/node_modules/npm
```
Closing...
