### ISSUE TITLE
TypeError: Object #<Object> has no method 'binding' at (child_process.js:762:11)

### ISSUE THREAD

**Issue by BSteephenson** [joyent/node#9335]
tester.js
```
process = require('child_process')

var program = process.spawn('./a.out')
program.stdout.on('data', function(data){
	console.log("data : " + data)
})
```
I get 

```

child_process.js:762
  process.binding('tcp_wrap');
          ^
TypeError: Object #<Object> has no method 'binding'
    at new ChildProcess (child_process.js:762:11)
    at Object.exports.spawn (child_process.js:726:15)
    at Object.<anonymous> (stuff/tester.js:3:23)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

That seems like an error that should be caught by child_process itself

**Comment by BSteephenson** [comment]
Sorry, I just realized my mistake (should be program.stdio.on...)
How can we make error messages more intuitive for debugging?
