### ISSUE TITLE
undefined is not a function in _http_outgoing.js#OutgoingMessage.end()

### ISSUE THREAD

**Issue by phanect** [joyent/node#9337]
I experienced following error. This seems happening in [_http_outgoing.js:529](https://github.com/joyent/node/blob/v0.12.0/lib/_http_outgoing.js#L529).

(Node version: 0.12.0, installed via NVM; OS: Kubuntu 14.10)

```javascript
TypeError: undefined is not a function
    at OutgoingMessage.end (undefined is not a function:529:10)
    at allFailed (/home/phanect/dev/notel-api/node_modules/geddy-passport/node_modules/passport/lib/middleware/authenticate.js:155:11)
    at attempt (/home/phanect/dev/notel-api/node_modules/geddy-passport/node_modules/passport/lib/middleware/authenticate.js:161:28)
    at Strategy.strategy.fail (/home/phanect/dev/notel-api/node_modules/geddy-passport/node_modules/passport/lib/middleware/authenticate.js:278:9)
    at Strategy.authenticate (/home/phanect/dev/notel-api/node_modules/geddy-passport/node_modules/passport-local/lib/strategy.js:75:17)
    at attempt (/home/phanect/dev/notel-api/node_modules/geddy-passport/node_modules/passport/lib/middleware/authenticate.js:342:16)
    at authenticate (/home/phanect/dev/notel-api/node_modules/geddy-passport/node_modules/passport/lib/middleware/authenticate.js:343:7)
    at /home/phanect/dev/notel-api/node_modules/geddy-passport/lib/passport/index.js:54:44
    at Object.exports.login (/home/phanect/dev/notel-api/node_modules/geddy-passport/lib/passport/index.js:51:10)
    at login (/home/phanect/dev/notel-api/app/controllers/auth.js:9:12)
```

It occurs when I run

```javascript
res.end('Bad Request');
```

`res` object is Node.js standard HTTP response object:

```javascript
{ resp: 
   { domain: 
      { domain: null,
        _events: [Object],
        _maxListeners: undefined,
        members: [Object] },
     _events: { prefinish: [Function: resOnFinish], finish: [Object] },
     _maxListeners: undefined,
     output: [],
     outputEncodings: [],
     outputCallbacks: [],
     writable: true,
     _last: false,
     chunkedEncoding: false,
     shouldKeepAlive: true,
     useChunkedEncodingByDefault: true,
     sendDate: true,
     _removedHeader: {},
     _hasBody: true,
     _trailer: '',
     finished: false,
     _hangupClose: false,
     _headerSent: false,
     socket: 
      { _connecting: false,
        _hadError: false,
        _handle: [Object],
        _host: null,
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: true,
        destroyed: false,
        bytesRead: 203,
        _bytesDispatched: 0,
        _pendingData: null,
        _pendingEncoding: '',
        server: [Object],
        _idleTimeout: 120000,
        _idleNext: [Object],
        _idlePrev: [Object],
        _idleStart: 17565079,
        parser: [Object],
        _paused: false,
        read: [Function],
        _consuming: true,
        _httpMessage: [Circular] },
     connection: 
      { _connecting: false,
        _hadError: false,
        _handle: [Object],
        _host: null,
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: true,
        destroyed: false,
        bytesRead: 203,
        _bytesDispatched: 0,
        _pendingData: null,
        _pendingEncoding: '',
        server: [Object],
        _idleTimeout: 120000,
        _idleNext: [Object],
        _idlePrev: [Object],
        _idleStart: 17565079,
        parser: [Object],
        _paused: false,
        read: [Function],
        _consuming: true,
        _httpMessage: [Circular] },
     _header: null,
     _headers: null,
     _headerNames: {} },
  domain: 
   { domain: null,
     _events: { error: [Function] },
     _maxListeners: undefined,
     members: [ [Object], [Object] ] },
  _events: 
   { prefinish: [Function: resOnFinish],
     finish: [ [Function], [Function] ] },
  _maxListeners: undefined,
  output: [],
  outputEncodings: [],
  outputCallbacks: [],
  writable: true,
  _last: false,
  chunkedEncoding: false,
  shouldKeepAlive: true,
  useChunkedEncodingByDefault: true,
  sendDate: true,
  _removedHeader: {},
  _hasBody: true,
  _trailer: '',
  finished: false,
  _hangupClose: false,
  _headerSent: false,
  socket: 
   { _connecting: false,
     _hadError: false,
     _handle: 
      { fd: 15,
        reading: true,
        owner: [Circular],
        onread: [Function: onread],
        onconnection: null,
        writeQueueSize: 0 },
     _host: null,
     _readableState: 
      { objectMode: false,
        highWaterMark: 16384,
        buffer: [],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null,
        resumeScheduled: false },
     readable: true,
     domain: null,
     _events: 
      { end: [Object],
        finish: [Function: onSocketFinish],
        _socketEnd: [Function: onSocketEnd],
        drain: [Object],
        timeout: [Function],
        error: [Function: socketOnError],
        close: [Object],
        data: [Function: socketOnData] },
     _maxListeners: undefined,
     _writableState: 
      { objectMode: false,
        highWaterMark: 16384,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        decodeStrings: false,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: true,
        bufferProcessing: false,
        onwrite: [Function],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: false,
        errorEmitted: false },
     writable: true,
     allowHalfOpen: true,
     destroyed: false,
     bytesRead: 203,
     _bytesDispatched: 0,
     _pendingData: null,
     _pendingEncoding: '',
     server: 
      { domain: null,
        _events: [Object],
        _maxListeners: undefined,
        _connections: 1,
        _handle: [Object],
        _usingSlaves: false,
        _slaves: [],
        allowHalfOpen: true,
        pauseOnConnect: false,
        httpAllowHalfOpen: false,
        timeout: 120000,
        _connectionKey: '4:127.0.0.1:4000' },
     _idleTimeout: 120000,
     _idleNext: { _idleNext: [Circular], _idlePrev: [Circular] },
     _idlePrev: { _idleNext: [Circular], _idlePrev: [Circular] },
     _idleStart: 17565079,
     parser: 
      { '0': [Function: parserOnHeaders],
        '1': [Function: parserOnHeadersComplete],
        '2': [Function: parserOnBody],
        '3': [Function: parserOnMessageComplete],
        _headers: [],
        _url: '',
        socket: [Circular],
        incoming: [Object],
        maxHeaderPairs: 2000,
        onIncoming: [Function: parserOnIncoming] },
     _paused: false,
     read: [Function],
     _consuming: true,
     _httpMessage: 
      { domain: [Object],
        _events: [Object],
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        writable: true,
        _last: false,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: true,
        sendDate: true,
        _removedHeader: {},
        _hasBody: true,
        _trailer: '',
        finished: false,
        _hangupClose: false,
        _headerSent: false,
        socket: [Circular],
        connection: [Circular],
        _header: null,
        _headers: null,
        _headerNames: {} } },
  connection: 
   { _connecting: false,
     _hadError: false,
     _handle: 
      { fd: 15,
        reading: true,
        owner: [Circular],
        onread: [Function: onread],
        onconnection: null,
        writeQueueSize: 0 },
     _host: null,
     _readableState: 
      { objectMode: false,
        highWaterMark: 16384,
        buffer: [],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null,
        resumeScheduled: false },
     readable: true,
     domain: null,
     _events: 
      { end: [Object],
        finish: [Function: onSocketFinish],
        _socketEnd: [Function: onSocketEnd],
        drain: [Object],
        timeout: [Function],
        error: [Function: socketOnError],
        close: [Object],
        data: [Function: socketOnData] },
     _maxListeners: undefined,
     _writableState: 
      { objectMode: false,
        highWaterMark: 16384,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        decodeStrings: false,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: true,
        bufferProcessing: false,
        onwrite: [Function],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: false,
        errorEmitted: false },
     writable: true,
     allowHalfOpen: true,
     destroyed: false,
     bytesRead: 203,
     _bytesDispatched: 0,
     _pendingData: null,
     _pendingEncoding: '',
     server: 
      { domain: null,
        _events: [Object],
        _maxListeners: undefined,
        _connections: 1,
        _handle: [Object],
        _usingSlaves: false,
        _slaves: [],
        allowHalfOpen: true,
        pauseOnConnect: false,
        httpAllowHalfOpen: false,
        timeout: 120000,
        _connectionKey: '4:127.0.0.1:4000' },
     _idleTimeout: 120000,
     _idleNext: { _idleNext: [Circular], _idlePrev: [Circular] },
     _idlePrev: { _idleNext: [Circular], _idlePrev: [Circular] },
     _idleStart: 17565079,
     parser: 
      { '0': [Function: parserOnHeaders],
        '1': [Function: parserOnHeadersComplete],
        '2': [Function: parserOnBody],
        '3': [Function: parserOnMessageComplete],
        _headers: [],
        _url: '',
        socket: [Circular],
        incoming: [Object],
        maxHeaderPairs: 2000,
        onIncoming: [Function: parserOnIncoming] },
     _paused: false,
     read: [Function],
     _consuming: true,
     _httpMessage: 
      { domain: [Object],
        _events: [Object],
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        writable: true,
        _last: false,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: true,
        sendDate: true,
        _removedHeader: {},
        _hasBody: true,
        _trailer: '',
        finished: false,
        _hangupClose: false,
        _headerSent: false,
        socket: [Circular],
        connection: [Circular],
        _header: null,
        _headers: null,
        _headerNames: {} } },
  _header: null,
  _headers: null,
  _headerNames: {},
  _geddyId: '324F5C83-4BC0-4C8D-A708-8346283BFB7F',
  controller: 
   { login: [Function],
     app: 
      { config: [Object],
        router: [Object],
        modelRegistry: {},
        templateRegistry: [Object],
        controllerRegistry: {},
        init: [Function],
        handleControllerAction: [Function],
        handleStaticFile: [Function],
        handleMethodNotAllowed: [Function],
        handleNotFound: [Function],
        handleNoMatchedRoute: [Function],
        handleNoAction: [Function],
        handleNoController: [Function],
        start: [Function],
        viewHelpers: [Object],
        mailer: [Object] },
     url: '/api/auth/login/local',
     method: 'POST',
     params: 
      { method: 'POST',
        controller: 'Auth',
        action: 'login',
        strategy: 'local',
        username: '09001234567',
        password: 'notel' },
     accessTime: 1425554952098,
     request: 
      { _readableState: [Object],
        readable: false,
        domain: [Object],
        _events: [Object],
        _maxListeners: undefined,
        socket: [Object],
        connection: [Object],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Object],
        trailers: {},
        rawTrailers: [],
        _pendings: [],
        _pendingIndex: 0,
        upgrade: false,
        url: '/api/auth/login/local',
        method: 'POST',
        statusCode: null,
        statusMessage: null,
        client: [Object],
        _consuming: true,
        _dumped: false,
        query: {},
        _geddyId: '324F5C83-4BC0-4C8D-A708-8346283BFB7F',
        controller: [Circular],
        read: [Function],
        body: 'username=09001234567&password=notel',
        session: {} },
     response: [Circular],
     name: 'Auth',
     cookies: { collection: {} },
     i18n: 
      { getLocale: [Function],
        setLocale: [Function],
        getText: [Function],
        t: [Function] },
     getLocale: [Function],
     setLocale: [Function],
     session: 
      { id: 'ECCNVRLkCIAh76fCqXFOwHxAnMsZ6or6ClaEYXZeKdoHRHTz5uCaYN1UoG7fs5QXZ8yqpO5ll9AbjUqdSnGfzdV1c1eTosWxiMEPR4WU8AuHBM53UEwcuhaAIj6l4jsP',
        expiry: 1209600000,
        cookies: [Object],
        accessTime: 1425554952098,
        data: {},
        flash: [Object] },
     flash: 
      { session: [Object],
        used: [],
        messages: {},
        messagesArr: [],
        config: undefined },
     sameOriginToken: '459dc5b3a0ba49b344ca5b9c24657b90ced0ea86' } }
```

Above info may not be enough. Can you tell me what additional info is required?

**Comment by cjihrig** [comment]
It looks like the error is happening in passport. Are you able to provide a runnable example that reproduces the issue without any external dependencies such as passport?

**Comment by phanect** [comment]
I digged code and I found this may be because of Geddy, the framework I use. I received response object from Geddy, and the response object is modified by Geddy.

This doesn't seem error of Node.js itself, so I close this for now. If this is a problem which is derived from Node, I will reopen it.
