### ISSUE TITLE
DataView prototype is missing..

### ISSUE THREAD

**Issue by Wandalen** [joyent/node#9425]
Seems DataView prototype is missing getUint8,setUint8,getUint16,setUint16,getUint32 and other methods. Code like this does not work:
```
var getView = DataView.prototype.getUint8;
```
This hack helps:
```
var _arrayBufferPrototypeHack = new DataView( new ArrayBuffer( 1 ), 0, 0 );
var getView = _arrayBufferPrototypeHack.getUint8;
```
But it is hack.
This drawback makes porting from jscript to nodejs's dialect more difficult.
Also this:
```
new DataView( new ArrayBuffer( 0 ), 0, 0 )
```
Gives exception, but should not.

**Comment by jasnell** [comment]
Hmm... doesn't appear to be an issue here:
```
bash-3.2$ node --version
v0.12.0
bash-3.2$ node
> console.log(DataView.prototype.getUint8)
[Function: getUint8]
undefined
> 
```
mac osx 10.10, v0.12

**Comment by Wandalen** [comment]
Hello,

```
(< node -e "console.log( new DataView( new ArrayBuffer( 0 ), 0, 0 ) )"
node -e "console.log( DataView.prototype.getUint8 )"
undefined
```
```
console.log( new DataView( new ArrayBuffer( 0 ), 0, 0 ) )
             ^
RangeError: byteOffset out of range.
    at [eval]:1:14
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:536:25)
    at startup (node.js:80:7)
    at node.js:906:3
```
```
 node --version
v0.10.29
```

Seems update helped. It's risky to make updates, because all the time I do it, I encounter unpleasant surprises. 

Thanks, please close.
